### ISSUE TITLE
Won't build android on phonegap build service

### ISSUE THREAD

**Issue by niallel** [pushandplay/cordova-plugin-apprate#100]
iOS and Windows build fine, but for Android I get the following error message

Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: InAppBrowser.java

Any ideas how to fix this?

**Comment by 2803media** [comment]
Is anybody find a solution for this problem? Google ask developer to update their app to phonegap 4.1.1...

**Comment by Dineshrajaa** [comment]
Using this 
<plugin name="cordova-plugin-apprate" spec="https://github.com/pushandplay/cordova-plugin-apprate.git" />
in the config.xml helped me to build in build.phonegap.com service

**Comment by westonganger** [comment]
This plugins `plugin.xml` was recently updated. Can you try updating to the latest version (1.1.9 currently) and let me know if this is still an issue.
