### ISSUE TITLE
Rename dependency

### ISSUE THREAD

**Issue by sungwoncho** [pushandplay/cordova-plugin-apprate#101]
`org.apache.cordova.globalization` has changed its name to `cordova-plugin-globalization`, and so has `org.apache.cordova.dialogs` to `cordova-plugin-dialogs`. It'd be good to change the dependency name. Any thoughts?

**Comment by DanDance** [comment]
i made a pull request for it, you may now install plugin with  `cordova plugin add https://github.com/DanDance/cordova-plugin-apprate/`

**Comment by westonganger** [comment]
Fixed in #90
