### ISSUE TITLE
doesn't build on latest ios

### ISSUE THREAD

**Issue by ihadeed** [pushandplay/cordova-plugin-apprate#102]

**Comment by Joncom** [comment]
@ihadeed, [this one](https://github.com/speige/cordova-plugin-apprate) builds for me, FYI.

**Comment by degamer106** [comment]
I literally just installed this plugin today into our Ionic Project and it works fine in iOS 9.2.

**Comment by ihadeed** [comment]
That's strange.. must have been conflicting with another plugin or something. 
I will test again soon.

**Comment by Joncom** [comment]
Doesn't compile on iOS 9.2 for me. 
Pull requests #90 and #92 apparently fix the problem.
The fork I linked to earlier includes these fixes.

**Comment by westonganger** [comment]
Fixed in #90
