### ISSUE TITLE
Cannot build on Phonegap Build and How to make it work?

### ISSUE THREAD

**Issue by alij2016** [pushandplay/cordova-plugin-apprate#109]
Hi @westonganger,

I am using Phonegap Build and I added this plugin in my config.xml file like this: 

` <gap:plugin name="cordova-plugin-apprate"/>`

However, I cannot get it to buld because I get this:

**_Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: InAppBrowser.java_**

Second question, I see there are dependencies for this, must I include them even I am using Phonegap Build?

Third question is how to get it work? I add the plugin in config/xml and then? Copy these lines on my index.html file in head section? It will work automatically if I do this?

```
var customLocale = {};
customLocale.title = "Rate %@";
customLocale.message = "If you enjoy using %@, would you mind taking a moment to rate it? It won’t take more than a minute. Thanks for your support!";
customLocale.cancelButtonLabel = "No, Thanks";
customLocale.laterButtonLabel = "Remind Me Later";
customLocale.rateButtonLabel = "Rate It Now";

AppRate.preferences.openStoreInApp = true;
AppRate.preferences.storeAppURL.ios = '<my_app_id>';
AppRate.preferences.storeAppURL.android = 'market://details?id=<package_name>';
AppRate.preferences.customLocale = customLocale;
AppRate.preferences.displayAppName = 'My custom app title';
AppRate.preferences.usesUntilPrompt = 5;
AppRate.preferences.promptAgainForEachNewVersion = false;
AppRate.promptForRating();
```

Thank you

**Comment by elbidone** [comment]
I use cordova-plugin-apprate and phonegap build I've removed it on my new builds because phonegap build cannot retrieve latest version. It always install version 1.1.7 that crashes my App. I've created an [issue to phonegap community](http://community.phonegap.com/nitobi/topics/my-installed-plugin-version-it-different-of-version-setted-on-config-xml)

**Comment by westonganger** [comment]
I use cordova, not phonegap so I can't test this. Is this an issue with PhoneGap build? Is this issue still occuring?

**Comment by elbidone** [comment]
`PhoneGap Build` builds the app with recent versions of plugin if you use cli-6.0.0 but continues using the work version if not use `plugin name="cordova-plugin-apprate" spec="https://github.com/pushandplay/cordova-plugin-apprate.git"`

So I don't think it's a `cordova-plugin-apprate` issue.
