### ISSUE TITLE
npm is still on version 1.1.11 instead 1.1.19

### ISSUE THREAD

**Issue by zwacky** [pushandplay/cordova-plugin-apprate#110]
just a heads up: can't get latest version through cordova/ionic via npm with `ionic plugin add cordova-plugin-apprate@1.1.19`. intentional?
cheers

**Comment by westonganger** [comment]
the latest version is `cordova-plugin-apprate@1.1.9` notice the 9 not 19

**Comment by zwacky** [comment]
shoot, you're right!

although the npm version does install a *1.1.11* version, which doesn't really add up... (https://www.npmjs.com/package/cordova-plugin-apprate)

also the `ionic plugin add cordova-plugin-apprate` resolves to the 1.1.11 version.

**Comment by westonganger** [comment]
This is because a fork has been registered with this name on the NPM registry. I have sent the owner an email. Hopefully we can get this name pointed back to this repo quickly.

**Comment by westonganger** [comment]
The NPM registry now correctly points to this repo (`pushandplay/cordova-plugin-apprate`) and has been bumped to version `1.1.12`

**Comment by zwacky** [comment]
**ionic plugin add cordova-plugin-apprate@1.1.12 --save**
```
Updated the hooks directory to have execute permissions
Fetching plugin "cordova-plugin-apprate@1.1.12" via npm
Error: Failed to fetch plugin cordova-plugin-apprate@1.1.12 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: version not found: cordova-plugin-apprate@1.1.12
```
also https://www.npmjs.com/package/cordova-plugin-apprate says it's on 0.1.9.

and installing without a `@version` it installs version 1.1.7 (although this could be my cache)

**Comment by westonganger** [comment]
Sorry, I forgot to run `npm publish` it shows 1.1.12 on npm now.
