### ISSUE TITLE
Random app crashes after installing apprate plugin [$100]

### ISSUE THREAD

**Issue by tripti-cipl** [pushandplay/cordova-plugin-apprate#116]
Hi Support Team,

We are developing app using phonegap cordova.We are getting random crashes on app startup due to apprate plugin.The crash error log is pointing to line "[self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];".

Kindly let us know how we can resolve this issue asap.

Thanks
Tripti Poddar
##

**Comment by westonganger** [comment]
Can you post some relevant portions of your app and the errors for this. This issue is pretty vague without details.

**Comment by tripti-cipl** [comment]
Hi Weston,

We are using cordova version 6.1.0 and xcode version 6.4

We are calling the code given below on body load.

var customLocale = {};
                customLocale.title = "Rate CDFF";
                customLocale.message = "If you enjoy using CDFF, would you mind taking a moment to rate it? It won’t take more than a minute. Thanks for your support!";
                customLocale.cancelButtonLabel = "No, Thanks";
                customLocale.laterButtonLabel = "Remind Me Later";
                customLocale.rateButtonLabel = "Rate It Now";
                
                
                AppRate.preferences.storeAppURL.ios = '625001689';
                AppRate.preferences.customLocale = customLocale;
                
                AppRate.preferences.usesUntilPrompt = 10;
                AppRate.promptForRating(false);

We check the crash report of the device and found the error given below-
Thread 1 name:  Dispatch queue: com.apple.root.default-qos
Thread 1 Crashed:
Christian Dating       0x000f828e __26-[CDVAppRate getAppTitle:]_block_invoke (CDVAppRate.m:39)

It seems that app crashes in between 10 to 20 session everytime.Please check this and let me know if any further information is required.

Thanks and Regards
Tripti Poddar

**Comment by westonganger** [comment]
More importantly, if you could possibly post the contents of this file `/platforms/ios/YourProjectName/YourProjectName-Info.plist`

**Comment by tripti-cipl** [comment]
Hi Weston,

We are not using cordova hooks in our app.Also I have sent you .plist file that we are using in our app on your email address "westonganger@gmail.com".Please check and let me know if anything else needed.

Thanks and Regards
Harshit Jalhotra

**Comment by tripti-cipl** [comment]
Hi Weston,

We are waiting for your response on this issue.Please let us know if you will fix this or not?

Thanks and Regards
Tripti Poddar

**Comment by lunchbag** [comment]
@tripti-cipl 
I ran the snippet that you posted and everything works fine for me.
Your Xcode version is pretty old, though. I wonder if updating to the latest (7.3.1) would make a difference. I find that that's often the culprit when things are crashing.

**Comment by westonganger** [comment]
v1.3.0 released please try that if you are having issues. Going to close this as its old.
