### ISSUE TITLE
Your request produced an error '[newNullResponse]'

### ISSUE THREAD

**Issue by Resham143** [pushandplay/cordova-plugin-apprate#118]
This message appears when i click on rate now button 
##

**Comment by snowbreeze** [comment]
Same here
```
try{
  AppRate.preferences.storeAppURL.ios = '1114015098';
  AppRate.preferences.storeAppURL.android = 'market://details?id=com.avifa.regularli';
}
catch(e){
    console.log(e)
}
```

Android works. iOS does not. I hope I gave the correct app id

**Comment by snowbreeze** [comment]
Console catches
```
ReferenceError {} 
```

**Comment by andreaj8** [comment]
i'v the the same error on iOS

**Comment by thomashrabe** [comment]
Any solution to this yet? I see the same...

**Comment by thomashrabe** [comment]
I am not sure, but from reading other posts my guess is that the iOS URL that's generated internally might have changed?

**Comment by thomashrabe** [comment]
@snowbreeze I tried your way but `storeAppURL.ios` was undefined. Maybe that relates to your error?

**Comment by thomashrabe** [comment]
Figured out at least one way how to fix this. You have to make sure you call everything after `platform.ready`.
