### ISSUE TITLE
Keeps asking for rating

### ISSUE THREAD

**Issue by vespino** [pushandplay/cordova-plugin-apprate#122]
The current version of the plugin keeps asking to rate, even when the settings say ask after x times. These are my settings:

		var customLocale = {};
		customLocale.title = "Rate this app";
		customLocale.message = 'Happy with this app? Rate this with 5 stars in the '+(device.platform=='Android' ? 'Play Store' : 'App Store')+'. It only takes a minute. Thanks for your support!';
		customLocale.cancelButtonLabel = "No, thanks";
		customLocale.laterButtonLabel = "Rate later";
		customLocale.rateButtonLabel = "Rate now";
		
		AppRate.preferences.openStoreInApp = true;
		AppRate.preferences.storeAppURL.ios = '958968104';
		AppRate.preferences.customLocale = customLocale;
		AppRate.preferences.displayAppName = 'deze app';
		AppRate.preferences.usesUntilPrompt = 10;
		AppRate.preferences.promptAgainForEachNewVersion = true;
		AppRate.promptForRating();

**Comment by vespino** [comment]
v1.1.9 works without the issue, so I rolled back to that hoping for a quick fix.

**Comment by kristfal** [comment]
The API was changed in the latest version. Call AppRate.promptForRating(false) and it will respect the counter and user input.

**Comment by vespino** [comment]
Ok, I will test it next time I have a project. Thank you.
