### ISSUE TITLE
change ios app store url

### ISSUE THREAD

**Issue by gaurav-chandra** [pushandplay/cordova-plugin-apprate#123]
The current version has the following default ios url:
```
http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewContentsUserReviews?pageNumber=0&sortOrdering=1&type=Purple+Software&mt=8&id=
```
this gets prepended to the app id for iOS. This is not working on iOS 9.3+. This needs to be changed to:
```
itms-apps://itunes.apple.com/app/
```
for it to work. I had to manually change the js file for it.

**Comment by kristfal** [comment]
I can confirm this issue. Alternative workaround is to initialize with preference:

`openStoreInApp: true`

which will circumvent the broken URL by opening the store in a native sub-view.

**Comment by akofman** [comment]
This workaround is unfortunately not ideal because of this existing restriction : http://stackoverflow.com/questions/36544926/does-skstoreproductviewcontroller-allow-to-rate-an-app-write-a-review

I think it's better to fix this problem and then removing the `openStoreInApp` option actually.

**Comment by akofman** [comment]
I just tested it on iOS 9.3.2 and it works well with the `http://itunes.apple.com/` format.

**Comment by amuramoto** [comment]
For deep linking to the reviews tab this pattern works: itms-apps://itunes.apple.com/app/viewContentsUserReviews/id<ITUNES_CONNECT_APP_ID>.

I've sent https://github.com/pushandplay/cordova-plugin-apprate/pull/137 to include this.
