### ISSUE TITLE
Wrong documentation [Don't Call rate dialog immediately]

### ISSUE THREAD

**Issue by fentas** [pushandplay/cordova-plugin-apprate#124]
Heyho,
I have an ionic project. If I have `customLocale` within `AppRate.preferences = {...}` `usesUntilPrompt` seems to be ignored. Prompt shows up every time on startup.. Also if I press "No thanks".

**Comment by fentas** [comment]
Wrong documentation...
> If false is present it will ignore usesUntilPrompt, promptAgainForEachNewVersion, and button logic, it will prompt every time.

Should be `If false is `**not**` present it will ignore [...] it will prompt every time`.

**Comment by westonganger** [comment]
Fixed the documentation. Thanks for your improvement.
