### ISSUE TITLE
Plugin undefined

### ISSUE THREAD

**Issue by hershko** [pushandplay/cordova-plugin-apprate#130]
I've installed the plugin (on a Cordova project) by doing "cordova plugins add cordova-plugin-apprate". If I run "cordova plugin list" I can indeed see it in the list (it's showing up as cordova-plugin-apprate 1.1.12 "AppRate").

However, I can't actually access the plugin in the project. It remains undefined (i.e. typeof AppRate === 'undefined'). Am I missing something?

I tried removing and adding the android platform (just in case), but that didn't help either. Any ideas? Thanks!
##

**Comment by jorge8989** [comment]
Same here, let me know if you find a solution

**Comment by robertoibarra** [comment]
+1

**Comment by garyconstable** [comment]
same here - its undefined.

**Comment by robertoibarra** [comment]
I found out you have to call it AFTER the onDeviceReady method is triggered, then it works perfectly: 

var app = {
    // Application Constructor
    initialize: function() {
        document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);
    },

    // deviceready Event Handler
    //
    // Bind any cordova events here. Common events are:
    // 'pause', 'resume', etc.
    onDeviceReady: function() {
HERE IT THE VAR IS NOT UNDEFINED ANYMORE

**Comment by westonganger** [comment]
All cordova plugins must be used within `onDeviceReady`. Closing
