### ISSUE TITLE
Dismiss the Apprate dialog in Android.

### ISSUE THREAD

**Issue by ankushgoyal27** [pushandplay/cordova-plugin-apprate#133]
Issue: When Apprate dialog appears in Android, then user touches to any other place on the screen, it capture the event and show button index as "0" and the dialog box fade out. This happens only for Android.

In iOS, when user touch to any of the buttons then only it capture the event and dialog box dismiss, 

Please suggest.
##

**Comment by 7h3m4dS0u1** [comment]
HI @ankushgoyal27,
this is my solution.
Note "case 0:"

'''javascript
 promptForRatingWindowButtonClickHandler = function(buttonIndex) {
    var base;
    switch (buttonIndex) {
      case 1:
        updateCounter('stop');
        AppRate.navigateToAppStore();
        break;
      case 2:
        updateCounter('reset');
        break;
      case 3:
        updateCounter('stop');
        break;
      case 0:
        updateCounter('reset');  
    }
'''

**Comment by ankushgoyal27** [comment]
Thanks for solution. We can close this issue.
