### ISSUE TITLE
How to test app rate for android if you need the app to already be in store for app rate to work?

### ISSUE THREAD

**Issue by Mahopacs** [pushandplay/cordova-plugin-apprate#135]
Does anyone have any experience with the app rate plugin (specifically for android)?  The confusion I have is it seems in order to use this code your app ALREADY has to be in the app store.

If that is in fact true, how can I initially release my app to the android store and be confident the rating functionality is working?

The code I am using is:

AppRate.preferences.storeAppURL = {
 ios: '<my_app_id>',
 android: 'market://details?id=<package_name>',
 windows: 'ms-windows-store://pdp/?ProductId=<the apps Store ID>',
 blackberry: 'appworld://content/[App Id]/',
 windows8: 'ms-windows-store:Review?name=<the Package Family Name of the application>'
};

AppRate.promptForRating();
##

**Comment by alejandrocao** [comment]
I think before uploading your app to Play Store you will know the package name (so you have to setup it right), but if you want to try if the plugin is working before publish the app, you could try using another app already available in the app store... That works for me!

**Comment by Mahopacs** [comment]
Thank you for the reply.
My package name is set to: com.tedjyoung.hereiam in my config/xml file.
My code is below, As you can see I am setting:
android: 'market://details?id=com.tedjyoung.hereiam',

Do you see anything I am doing wrong?
When I click my button that executes the  AppRate.promptForRating(false) line, all I get is a white blank screen.

I have already deployed my app so this is how it is working when I download the app from the android store...
Thank you!
Ted



AppRate.preferences = {    useLanguage: 'en',    openStoreInApp: true,    displayAppName: 'Here I Am',    usesUntilPrompt: 5,    promptAgainForEachNewVersion: false,    storeAppURL: {        ios: '<my_app_id>',        android: 'market://details?id=com.tedjyoung.hereiam',        windows: 'ms-windows-store://pdp/?ProductId=<the apps Store ID>',        blackberry: 'appworld://content/[App Id]/',        windows8: 'ms-windows-store:Review?name=<the Package Family Name of the application>'    },    customLocale: {        title: "Rate 'Here I Am'",        message: "If you enjoy using 'Here I Am', would you mind taking a moment to rate it? It won’t take more than a minute. Thanks for your support!",        cancelButtonLabel: "No, Thanks",        laterButtonLabel: "Remind Me Later",        rateButtonLabel: "Rate It Now"    }};
AppRate.preferences = {    useCustomRateDialog: true,    callbacks: {        onRateDialogShow: function (callback) {            callback(1) // cause immediate click on 'Rate Now' button         },        onButtonClicked: function (buttonIndex) {            console.log("onButtonClicked -> " + buttonIndex);        }    }};
function rateHereIAm() {    try {        AppRate.promptForRating(false);    } catch (e) {        alert("Error rating app.  Error = " + e.message);    }}



    On Wednesday, September 7, 2016 11:41 PM, Alejandro <notifications@github.com> wrote:
 

 I think before uploading your app to Play Store you will know the package name (so you have to setup it right), but if you want to try if the plugin is working before publish the app, you could try using another app already available in the app store... That works for me!—

**Comment by alejandrocao** [comment]
If you want to get the app rate dialog immediately when you click the button, i think you should call AppRate.promptForRating(true);

You invoke the method with false, so it will use your usesUntilPrompt parameter, that is set to 5, so you it will show the dialog after 5 app runs. 

I think you should could change the invocation to a device ready function or leave the invocation in the button click function but change the parameter to true.
