### ISSUE TITLE
1.3.0 not published to NPM

### ISSUE THREAD

**Issue by mcoenca** [pushandplay/cordova-plugin-apprate#139]
Hello ! Your latest version is not published to npm :)
see https://www.npmjs.com/package/cordova-plugin-apprate 

![image](https://cloud.githubusercontent.com/assets/6507140/18986677/3a8203aa-86fe-11e6-9306-a9a94264683d.png)

Thanks, best.
##

**Comment by betko** [comment]
Hello! 😺  I would like to use the latest version of the plugin also. When can I expect the publication to the npm registry?

**Comment by geshub** [comment]
Still not on npm :(

**Comment by dawuwu** [comment]
is this project abandoned?

**Comment by westonganger** [comment]
v1.3.0 has now been released.
