### ISSUE TITLE
Error while showing while popup window

### ISSUE THREAD

**Issue by ranvirgorai** [pushandplay/cordova-plugin-apprate#141]
_onPopup:_ Uncaught TypeError: Cannot read property **'onRateDialogShow**' of undefined

**on click rate now:**cordova.js:314 Uncaught TypeError: Cannot read property **'onButtonClicked'** of undefined
##

**Comment by barocsi** [comment]
+1

**Comment by polomani** [comment]
the same for me

**Comment by vinodpandey** [comment]
+1

**Comment by westonganger** [comment]
I just released v1.3.0 which fixes this bug of undefined callbacks.

**Comment by abitul** [comment]
@ranvirgorai  , u can use following code, it's work for me 

          this.appRate.promptForRating(true);
          this.appRate.preferences = {
            usesUntilPrompt: 3,
            storeAppURL: {
             ios: "com.abi.murottaloffline",
             android: "market://details?id=com.abi.murottaloffline",
             windows: "ms-windows-store://review/?ProductId=com.abi.murottaloffline"
            },
            callbacks: {
              onRateDialogShow: function(callback){
                console.log("onRateDialogShow");
              },
              onButtonClicked: function(buttonIndex){
                console.log("onButtonClicked");
              },
              handleNegativeFeedback: function(buttonIndex){
                console.log("handleNegativeFeedback");
              },
            }
          };
