### ISSUE TITLE
App Store doesn't open in iOS10. `openStoreInApp=false` doesn't work on iOS10.

### ISSUE THREAD

**Issue by mjurczyk** [pushandplay/cordova-plugin-apprate#145]
If we set `openStoreInApp` to _false_ in the preferences, AppStore isn't opened as en external application. No error is thrown, just no reaction at all (for both custom and navigator.confirm dialogs).
Works perfectly with `openStoreInApp` set to _true_ though.

**Comment by SharkChips** [comment]
Same here. This is a huge issue.

**Comment by johnborges** [comment]
+1 
Doesn't work for me either on iOS 10 regardless of `openStoreInApp: <true|false>`. Works fine in iOS < 10.0

**Comment by geshub** [comment]
It's working for me with openStoreInApp set to true on IOS 10.2 ( iphone 6 ) but nothing happens if it's set to false.

**Comment by geshub** [comment]
Also, if openStoreInApp is set to true, the app store page opens for me, but i can't actually review the app, **nothing happens on pressing the review link**. So basically you can't review on IOS 10 with openStoreInApp set to true or false.
Did anyone else noticed this problem ?

**Comment by ahar** [comment]
@geshub Yes, I'm experiencing this problem too. How did you solved it?

**Comment by geshub** [comment]
@ahar I couldn't solve it yet, i deactivated the plugin for now.
Just checking again if someone could make this plugin work with IOS 10 ?

**Comment by jbw91** [comment]
This is a huge issue for me as well. It works properly on Android, but using an iPhone it will not open.

**Comment by esmiralha** [comment]
Works for me on iOS 10.2.

**Comment by westonganger** [comment]
I just released v1.3.0 are you still experiencing these issues?

**Comment by geshub** [comment]
It's working perfectly for me now on IOS 10.3.1, thanks a lot for the update !
