### ISSUE TITLE
%@ patterns in customLocale object not replaced with the title

### ISSUE THREAD

**Issue by mourice** [pushandplay/cordova-plugin-apprate#147]
%@ is not replaced with the app title. Dialog shown with the %@ 

![screenshot_20161122-145345](https://cloud.githubusercontent.com/assets/1805296/20477234/af46fb62-affa-11e6-9bed-020e7fe66257.jpg)

**Comment by westonganger** [comment]
This was related to using a customLocale. Just release v1.3.0 which fixes this.
