### ISSUE TITLE
Cannot get popup to show

### ISSUE THREAD

**Issue by mjtaljaard** [pushandplay/cordova-plugin-apprate#150]
Please help. I cannot get the popup to show. What am I doing wrong?
Loaded into the config:

```
<!-- PhoneGap plugins -->
<plugin name="cordova-plugin-dialogs" spec="~1.3.0" />
<plugin name="cordova-plugin-globalization" spec="~1.0.5" />
    
    <!--AddedRateMyApp-->
<plugin name="cordova-plugin-apprate" spec="1.2.0" source="npm" />
```

and in my index file:

```
<script type="text/javascript" charset="utf-8"> 
function onLoad() {
        document.addEventListener("deviceready", onDeviceReady, false);
    }
    
function onDeviceReady() {
    AppRate.preferences.storeAppURL = {
    ios: '1182752076'
    };

    AppRate.promptForRating();
    }
</script>       

  </head>
    
<body onload="onLoad()">
```

**Comment by robertoibarra** [comment]
I'm having the same issue, new project, add the plugin from git (ver 1.3.0) directly and this code:
<script type="text/javascript" >alert(typeof AppRate);</script>
Says AppRate is undefined
I've only tested on android. please help, great plugin!

**Comment by robertoibarra** [comment]
After some fiddling, it seems AppRate is only populated after the onDeviceReady() in index.js is executed. This code seems to work as an example (from index.js):

var app = {
    // Application Constructor
    initialize: function() {
        document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);
    },

    // deviceready Event Handler
    //
    // Bind any cordova events here. Common events are:
    // 'pause', 'resume', etc.
    onDeviceReady: function() {
        //this.receivedEvent('deviceready');
        
		AppRate.preferences.storeAppURL = {
			android: 'market://details?id=com.catolicapp.misal'
		};

		AppRate.promptForRating();        
                
    },
........ rest of the code from index.js
