### ISSUE TITLE
error locales

### ISSUE THREAD

**Issue by LuigiFerrante** [pushandplay/cordova-plugin-apprate#151]
Is necessary this?
|| locales[language.split(/-/)[0]] 
into locales.js row 52.

**Comment by dawuwu** [comment]
Yes, to identify the correct locale, since some locales are shown like en-us, en-gb etc

**Comment by LuigiFerrante** [comment]
Ok, but my question is: is it correct?
Or is better language.split('-')[0].
Sorry if it's a stupid question.

**Comment by erperejildo** [comment]
Getting this issue now:

> Uncaught (in promise): TypeError: Cannot read property 'split' of undefined TypeError: Cannot read property 'split' of undefined at Function.Locales.getLocale (http://192.168.1.2:8100/plugins/cordova-plugin-apprate/www/locales.js:53:74) at showDialog (http://192.168.1.2:8100/plugins/cordova-plugin-apprate/www/AppRate.js:91:29) at Function.AppRate.promptForRating (http://192.168.1.2:8100/plugins/cordova-plugin-apprate/www/AppRate.js:203:7) at callCordovaPlugin (http://192.168.1.2:8100/build/vendor.js:77234:43) at http://192.168.1.2:8100/build/vendor.js:77260:28 at http://192.168.1.2:8100/build/vendor.js:58635:17 at new t (http://192.168.1.2:8100/build/polyfills.js:3:20886) at tryNativePromise (http://192.168.1.2:8100/build/vendor.js:58634:20) at getPromise (http://192.168.1.2:8100/build/vendor.js:58642:12) at wrapPromise (http://192.168.1.2:8100/build/vendor.js:77243:78)

Could be this related?

**Comment by ndrake** [comment]
@erperejildo I was just seeing this same error.  Turned out to be a problem with how I was setting up AppRate.preferences.  I wasn't setting a value for useLanguage, which resulted it it being 'undefined' instead of null (the default).  Once I added "useLanguage: null" to my AppRate.preferences object I no longer got the 'split' error.
