### ISSUE TITLE
Is requestReview api from SKStore​Review​Controller implemented for quick user reviews?

### ISSUE THREAD

**Issue by vivekpd15** [pushandplay/cordova-plugin-apprate#160]
Apple has released an API for providing App Store Ratings and Reviews directly. Is this included in the plugin?

https://developer.apple.com/library/content/releasenotes/General/WhatsNewIniOS/Articles/iOS10_3.html

**Comment by omaxlive** [comment]
Hi @vivekpd15 Here's a plugin made for that: https://github.com/omaxlive/com.omarben.inappreview
