### ISSUE TITLE
Use app store "?action=write-review" parameter

### ISSUE THREAD

**Issue by dorgold** [pushandplay/cordova-plugin-apprate#161]
Apple has recently added the option to append `?action=write-review` query parameter to the store listing URL in order to be redirected directly to the "write review" section. It would be useful to send the users directly there.

(described in the bottom paragraph [here](https://developer.apple.com/reference/storekit/skstorereviewcontroller/2851536-requestreview))
`To automatically open a page on which users can write a review in the App Store, append the query parameter action=write-review to your product URL.`

**Comment by westonganger** [comment]
Would accept a PR for this.

**Comment by remisture** [comment]
+1
