### ISSUE TITLE
Plugin not triggering on Android

### ISSUE THREAD

**Issue by saintsatplay2015** [pushandplay/cordova-plugin-apprate#167]
Firstly, thanks for your work on this plugin - it's very much appreciated.

I'm using Ionic 3.4 to build an app on iOS & Android.

The AppRate plugin works perfectly on iOS but doesn't trigger on Android.
The click handler is working (as this triggers the AppRate modal window on iOS) but nothing is ever displayed on Android.

Both platforms use the same codebase so I'm not sure why this is happening.

Could it be anything to do with minimum device/OS version?
I am testing on a Galaxy S4 Mini running Android 4.4.2.

If anyone has any suggestions/ideas I'm all ears!

Kind Regards

J

**Comment by NBAMj** [comment]
Strange, I'm using the latest ionic version *3.5.3* and its working fine.
Did you try to call [callbacks.onRateDialogShow](https://github.com/pushandplay/cordova-plugin-apprate/tree/v1.3.0#options--preferences) and insert a `console.log('test')` inside and check your log?
Is it ever reaching the log statement?
