### ISSUE TITLE
package.json missing when ionic cordova plugin add cordova-plugin-apprate is executed

### ISSUE THREAD

**Issue by sandeshgb** [pushandplay/cordova-plugin-apprate#170]
[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.
        
[ERROR] An error occurred while running cordova plugin add cordova-plugin-apprate --save (exit code 1):
        
        Error: Failed to fetch plugin cordova-plugin-apprate@^1.3.0 via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: npm: Command failed with exit code 1 Error output:
        npm ERR! code ENOLOCAL
        npm ERR! Could not install from "cordova-plugin-inappbrowser" as it does not contain a package.json file.
        
        npm ERR! A complete log of this run can be found in:
        npm ERR!     /home/eiosys/.npm/_logs/2017-06-30T11_05_23_318Z-debug.log

Providing you with log report:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'cordova-plugin-inappbrowser@^1.7.1',
1 verbose cli   '--save' ]
2 info using npm@5.0.3
3 info using node@v8.0.0
4 verbose npm-session 061df91b3c0aae0f
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/cordova-plugin-inappbrowser 773ms (from cache)
8 silly pacote range manifest for cordova-plugin-inappbrowser@^1.7.1 fetched in 809ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly fetchPackageMetaData error for cordova-plugin-inappbrowser@file:node_modules/cordova-plugin-inappbrowser Could not install from "cordova-plugin-inappbrowser" as it does not contain a package.json file.
13 verbose stack Error: ENOENT: no such file or directory, open '/var/www/html/excalibur-mobile/node_modules/cordova-plugin-inappbrowser/package.json'
14 verbose cwd /var/www/html/excalibur-mobile/node_modules
15 verbose Linux 4.4.0-83-generic
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "cordova-plugin-inappbrowser@^1.7.1" "--save"
17 verbose node v8.0.0
18 verbose npm  v5.0.3
19 error code ENOLOCAL
20 error Could not install from "cordova-plugin-inappbrowser" as it does not contain a package.json file.
21 verbose exit [ 1, true ]

**Comment by NBAMj** [comment]
package.json is missing from `cordova-plugin-inappbrowser` as its mentioned in your output, not from `cordova-plugin-apprate`

> `npm ERR! Could not install from "cordova-plugin-inappbrowser" as it does not contain a package.json file.`
