### ISSUE TITLE
package.json / plugin.xml are not up to date

### ISSUE THREAD

**Issue by jony89** [pushandplay/cordova-plugin-apprate#176]
version is still on 1.3.0

so for example when installing this plugin, the following PR code is missing : #156 

@pushandplay, please update version

**Comment by JimJty** [comment]
Yes, please fix. I am doing this in the mean time:

cordova plugin add https://github.com/pushandplay/cordova-plugin-apprate.git#05f5adf54e3e3a8294b2b083ef884bc106100297 --save

**Comment by jasonvdzeeuw** [comment]
@JimJty @pushandplay I've tried the current version as well as the following:
"cordova plugin add https://github.com/pushandplay/cordova-plugin-apprate.git#05f5adf54e3e3a8294b2b083ef884bc106100297 --save"

But I'm immediately getting the rate dialog, I wan't to be able to filter the negative feedback and callback these to their email, but I'm not getting the right version of the plugin I guess?
I double checked everything and SimpleMode = false.

Any solution for this?

**Comment by westonganger** [comment]
v1.4.0 released.
