### ISSUE TITLE
Add support for Windows Phone 8

### ISSUE THREAD

**Issue by pushandplay** [pushandplay/cordova-plugin-apprate#18]
##

**Comment by filipe-nunes** [comment]
Crashes on the following line:

> navigator.notification.confirm(localeObj.message, promptForRatingWindowButtonClickHandler, localeObj.title, [localeObj.cancelButtonLabel, localeObj.laterButtonLabel, localeObj.rateButtonLabel]);

Windows Phone 8.1 native dialog only allows two button.
