### ISSUE TITLE
iOS 11 Native review, "Submit" is not selectable

### ISSUE THREAD

**Issue by viking2917** [pushandplay/cordova-plugin-apprate#182]
After installing the apprate plugin, and attempting native app review, the Submit button is not selectable and no rating can be submitted.

Using the following installation step:
`cordova plugin add https://github.com/pushandplay/cordova-plugin-apprate.git`

app code:

 ```
$ionicPlatform.ready(function() {
	if(typeof AppRate !== 'undefined') {
	    AppRate.preferences.storeAppURL = {
		ios: '<my tag here>',
		android: 'market://details?id=<my tag here>'
	    };
	}

       AppRate.promptForRating();
}

```

menu displays, I pick 4 out of 5 stars, and the submit button is greyed out and not selectable, as shown in screenshot.

Any idea what might be wrong?

This is Ionic V1, IOS 11
![photo oct 11 11 20 26 am](https://user-images.githubusercontent.com/7691349/31468191-6e6cb0be-ae78-11e7-9dc0-b7e7270da665.png)

**Comment by viking2917** [comment]
Update: I am a moron. I put the Bundle ID, not the App ID. To be fair Apple doesn't help, in developer.apple.com, what they call the "ID" is really the Bundle ID, and no other ID is listed. But iTunes Connect makes this clear. 

Closing as "operator error".

**Comment by viking2917** [comment]
Update: even with the right ID, the Submit button stays greyed out. 

If I do,  AppRate.preferences.inAppReview = false, it works OK - launches to the App Store, where a rating can be left. 
But if I do  AppRate.preferences.inAppReview = false, I get the greyed out submit button. 

I'm not confident I have not made an error, but I think something is still wrong on iOS 11.

**Comment by vivekpd15** [comment]
+1

Facing the same issue. Any known workarounds?

**Comment by viking2917** [comment]
@vivekpd15 the only workaround I found was to use: 
AppRate.preferences.inAppReview = false
That launches the user to the App Store to review, which is much less convenient, but at least it's something.

**Comment by jmcrthrs** [comment]
https://stackoverflow.com/a/44258115

**Comment by vivekpd15** [comment]
@jmcrthrs Amazing. Thanks for this info.

Apple should be documenting such stuff. Gives devs a big pain.

**Comment by rolinger** [comment]
@vivekpd15  - It's Apple.  Users rave about Apple products...but I can never find a developer that raves about making apps for Apple.  I loathe Apple....its like they go out of their way to make developing for them as difficult as humanly possible.

**Comment by josteph** [comment]
This issue should be included in documentation. Some people might find this confusing.

**Comment by westonganger** [comment]
@josteph would happily accept a PR

**Comment by viking2917** [comment]
Closing, documentation has been updated per https://github.com/pushandplay/cordova-plugin-apprate/pull/246
