### ISSUE TITLE
Ionic 3 - NPM Error while installing plugin

### ISSUE THREAD

**Issue by gopalaiahvinay** [pushandplay/cordova-plugin-apprate#190]
Greetings,

I am trying to install the plugin,
But it is throwing errors referencing the **npm ERR! code EPEERINVALID** 

Pastebin Link: https://pastebin.com/embed_iframe/uKmnS55t

Screenshot: 
![image](https://user-images.githubusercontent.com/4154510/33195372-e94ca8c4-d0fc-11e7-81d2-ee7b41f3eccf.png)

Any help regarding this issue would be appreciated.

**Comment by petemcwilliams** [comment]
I am seeing something similar does the plugin have a peerdependency of npm?

**Comment by petemcwilliams** [comment]
npm ls npm

└─┬ cordova-plugin-apprate@1.3.0
  └─┬ cordova@7.1.0
    └─┬ cordova-lib@7.1.0
      └── npm@2.15.12

**Comment by YamanSehzade** [comment]
+1

**Comment by westonganger** [comment]
This was a result of a bug which is now fixed in #185. v1.4.0 now released.
