### ISSUE TITLE
Please provide better descriptions

### ISSUE THREAD

**Issue by rolinger** [pushandplay/cordova-plugin-apprate#192]
Could you please provide better descriptions in the Plugin description sections?  Especially pertaining to the callbacks:

```
  callbacks: {
    handleNegativeFeedback: function(){
      window.open('mailto:feedback@example.com','_system');
    },
    onRateDialogShow: function(callback){
      callback(1) // cause immediate click on 'Rate Now' button
    },
    onButtonClicked: function(buttonIndex){
      console.log("onButtonClicked -> " + buttonIndex);
    }
```

As well as the following:

> Don't Call rate dialog immediately
> 
> AppRate.promptForRating(false);
> If false is not present it will ignore usesUntilPrompt, promptAgainForEachNewVersion, and button logic, it will prompt every time.

This is a almost a triple negative.  Should this say, `"If true is present, it will ignore: usesUntilPrompt, promptAgainForEachNewVersion and button logic.  It will prompt the user every time."`  Is this accurate?

**Comment by jackvial** [comment]
The description could be better but the JS for the plugin is pretty straight forward so you should be able to get a better idea of what each method is doing by reading the source in AppRate.js

**Comment by selected-pixel-jameson** [comment]
So if my intention is to implement usesUntilPrompt and I not supposed to call AppRate.promptForRating at all? Or am I supposed to call it with false?
