### ISSUE TITLE
NPM Audit Vulnerabilities

### ISSUE THREAD

**Issue by Ruslancic** [pushandplay/cordova-plugin-apprate#208]
When i try to audit my App,  on console, i see the message: 
Critical        Command Injection

  

> Package         **open**
> 
>   Patched in      **No patch available**
> 
>   Dependency of   **cordova-plugin-apprate**
> 
>   Path            **cordova-plugin-apprate > cordova > cordova-lib >
>                   cordova-serve > open**
> 
>   More info       [https://nodesecurity.io/advisories/663](https://nodesecurity.io/advisories/663)

**Comment by eomonteiro** [comment]
+1

**Comment by westonganger** [comment]
It is possible this was a result of a bug which is now fixed in https://github.com/pushandplay/cordova-plugin-apprate/pull/185

I have released a new version. Is this still occurring with the new version?
