### ISSUE TITLE
How to skip popup with 3 asking buttons?

### ISSUE THREAD

**Issue by kurtiev** [pushandplay/cordova-plugin-apprate#214]
Is it possible to show final popup with starts?
I want just skip popup with 3  asking buttons(No Thanks, Remind Me Later, Rate It Now).

**Comment by xavier-villelegier** [comment]
@kurtiev Did you finally find a way to do this ? 🤔

**Comment by kurtiev** [comment]
Hi @xavier-villelegier, no i left it as it's.

**Comment by xavier-villelegier** [comment]
Thanks for your answer @kurtiev. And do you know if it's possible to skip the first modal then ? The one with "Do you like using…" - "Yes"/"No" ?

**Comment by kurtiev** [comment]
@xavier-villelegier Actually yes, by doc you can set `window.AppRate.preferences.simpleMode = true` and it's work for me.

**Comment by xavier-villelegier** [comment]
Oh my bad, I actually missed this one. Thanks man

**Comment by KiwiKilian** [comment]
You can directly skip the plugin popups by using `navigateToAppStore()`. If `inAppReview` is `true` and it hasn't already been prompted three times, it will show the in app dialogue on iOS, otherwise the App Store page.
