### ISSUE TITLE
Empty dialog with Ionic

### ISSUE THREAD

**Issue by cecodor** [pushandplay/cordova-plugin-apprate#215]
Don't know why but I follow all the instructions and guides, but I always get an empty dialog with null value buttons.

First, I install the plugin using the following command:

```
ionic cordova plugin add cordova-plugin-apprate
npm install --save @ionic-native/app-rate
```

Later, for testing purposes, I add this code after the platform.ready() line:

```
this.appRate.preferences = {
        displayAppName: 'Test App',
        usesUntilPrompt: 2,
        promptAgainForEachNewVersion: false,
        storeAppURL: {
          ios: '1216856883',
          android: 'market://details?id=com.devdactic.crossingnumbers'
        },
        customLocale: {
          title: 'Do you enjoy %@?',
          message: 'If you enjoy using %@, would you mind taking a moment to rate it? Thanks so much!',
          cancelButtonLabel: 'No, Thanks',
          laterButtonLabel: 'Remind Me Later',
          rateButtonLabel: 'Rate It Now'
        },
        callbacks: {
          onRateDialogShow: function(callback){
            console.log('rate dialog shown!');
          },
          onButtonClicked: function(buttonIndex){
            console.log('Selected index: -> ' + buttonIndex);
          }
        }
      };
 
      // Opens the rating immediately no matter what preferences you set
      this.appRate.promptForRating(true);
```

But all I get in my app is this:

![screenshot_20180701-122644](https://user-images.githubusercontent.com/23288172/42137031-e2132fb2-7d2a-11e8-82cd-f3c5ffbf54a6.jpg)

Any ideas?

Thanks!

**Comment by andelz** [comment]
Same for me. Looks like at least the current Android Version (8) has kind of a "Pre-Dialog" that says: "Do you like using XYZ?" [YES!] [NOT REALLY]. If you hit yes you'll get the actual dialog. Problem here is that there seem to be no proper translations. If I set useLanguage property on preferences to 'en', I get the message mentioned above. Switching to 'de' I get an empty dialog with 2 NULL buttons (left one is yes by the way, so if you hit the left NULL, you'll get your dialog). 

Is there a way to setup those translations as well, or at least get rid of the "Pre-Dialog"?

**Comment by Abdenasser** [comment]
It seems to be an issue with the latest version 1.4.0 use version 1.3.0 instead

**Comment by Alberick** [comment]
I'm currently using this version in production and for me it works nice just add the 

> yesButtonLabel 

and 

> noButtonLabel

. 


This is my object preferences.
`     this.appRate
            .preferences = {
            simpleMode: false,
            displayAppName: 'MiTUCson',
            usesUntilPrompt: 3,
            promptAgainForEachNewVersion: true,
            storeAppURL: {
                ios: '1398876880',
                android: 'market://details?id=com.tixif.mitucson',
            },
            customLocale: {
                title: 'Valora MiTUCson',
                message: '¿Te gustaría tomarte un minuto para calificar ' +
                'MiTUCson?¡Muchas Gracias!',
                cancelButtonLabel: 'No',
                laterButtonLabel: 'Luego',
                rateButtonLabel: 'Calificar',
                yesButtonLabel: 'Si!',
                noButtonLabel: 'No!',
                appRatePromptTitle: '¿Te gusta utilizar MiTUCson?',
                feedbackPromptTitle: '¿Te gustaría darnos tu opinión?'
            }
        };`

**Comment by gartorware** [comment]
I think this is just because of [missing translations here](https://github.com/pushandplay/cordova-plugin-apprate/blob/master/www/locales.js). We can either use simpleMode as suggested above or add our custom translations.
