### ISSUE TITLE
Error to open App Store

### ISSUE THREAD

**Issue by DualH** [pushandplay/cordova-plugin-apprate#216]
In this image show the error

[https://ibb.co/nbHKPy](https://ibb.co/nbHKPy)

The version of the plugin is 1.2.0, this version of the app is in distribution.

Help pls

**Comment by DualH** [comment]
@AndreasGassmann Hi!

[https://itunes.apple.com/uy/app/prex-card/id927400689](https://itunes.apple.com/uy/app/prex-card/id927400689)

This is my app the id is 927400689, its correct no?

**Comment by AndreasGassmann** [comment]
Yes, that's correct. In my case, I included "id", which was wrong. After I removed "id" and only used the numbers, it worked.
