### ISSUE TITLE
Plugin not working if language is not set to english

### ISSUE THREAD

**Issue by AndreasGassmann** [pushandplay/cordova-plugin-apprate#218]
## Problem 

So I just spent more time than I'm willing to admit on figuring this out, but it seems that the translations are only updated for English and Portuguese. All other languages are missing 4 strings that are required:

Complete translation:
```
{
  language: 'en',
  title: "Would you mind rating %@?",
  message: "It won't take more than a minute and helps to promote our app. Thanks for your support!",
  cancelButtonLabel: "No, Thanks",
  laterButtonLabel: "Remind Me Later",
  rateButtonLabel: "Rate It Now",
  yesButtonLabel: "Yes!",
  noButtonLabel: "Not really",
  appRatePromptTitle: 'Do you like using %@',
  feedbackPromptTitle: 'Mind giving us some feedback?',
  appRatePromptMessage:'',
  feedbackPromptMessage:''
}
```

Incomplete translation:
```
{
  language: 'de',
  title: "Bewerte %@",
  message: "Wenn dir %@ gefällt, würdest Du es bitte bewerten? Dies wird nicht länger als eine Minute dauern. Danke für die Unterstützung!",
  cancelButtonLabel: "Nein, danke",
  laterButtonLabel: "Später erinnern",
  rateButtonLabel: "Jetzt bewerten"
}
```

There is no mechanism for a fallback language, so when the plugin tries to launch the alert (I assume), the popup doesn't show and I get the following error message (on iOS):

```
Jul 20 07:28:53 iPhone AppName(CoreFoundation)[3568] <Notice>: -[NSNull isEqualToString:]: unrecognized selector sent to instance 0x1b5304650
Jul 20 07:28:53 iPhone AppName(WebKitLegacy)[3568] <Notice>: *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[NSNull isEqualToString:]: unrecognized selector sent to instance 0x1b5304650
```

## Solution

In my case I added the missing translations. You could also fix it by providing your own custom locale. Or the plugin could use english as a fallback so it at least works.

**Comment by Hissvard** [comment]
Wew, I spent quite some time wondering what I was doing wrong since nothing kept happening - thank you a ton.
I think falling back to english is the best solution.

**Comment by westonganger** [comment]
Would love a PR that sets this to english as fallback.
