### ISSUE TITLE
Only 15% of "Rate it now" shows up in the iOS App Store Ratings

### ISSUE THREAD

**Issue by chrishanyu** [pushandplay/cordova-plugin-apprate#234]
We track the click event when users click on "rate it now" button so it can gives us a sense of how many people rated the app upon AppRate asks for a review.  With 2 months of implementing this plugin, we've gotten around 500 unique clicks per user and only 100 increase in app store reviews. What might be the cause of the discrepancy? Does apple block most of the in-app ratings?

**Comment by guylando** [comment]
Android does not support in-app rating and users are just transition to store and might have not rated you there. I think the advanced mode is used to increase % of those who were redirected actually performing the review
