### ISSUE TITLE
ReferenceError: NativeStorage is not defined Ionic 4 (capacitor)

### ISSUE THREAD

**Issue by deveshmishra34** [pushandplay/cordova-plugin-apprate#237]
E/Capacitor/Plugin/Console: ERROR Error: Uncaught (in promise): ReferenceError: NativeStorage is not defined
    ReferenceError: NativeStorage is not defined
        at capacitor-runtime.js:3598:7
        at Promise (<anonymous>)
        at Object.get (capacitor-runtime.js:3597:12)
        at Function.AppRate.init (capacitor-runtime.js:2998:15)
        at capacitor-runtime.js:3110:9
        at build (capacitor-runtime.js:1127:13)
        at require (capacitor-runtime.js:1142:28)
        at localRequire (capacitor-runtime.js:1123:24)
        at Object.exports.mapModules (capacitor-runtime.js:2364:30)
        at capacitor-runtime.js:2288:26

Plugin Keep Crashing.

**Comment by lights0123** [comment]
I'm experiencing the same thing. The weird thing is, though, NativeStorage is defined, and manually calling it works.

**Comment by guylando** [comment]
Maybe its called as "NativeStorage" from inside a context where the global is now window?

**Comment by corysmc** [comment]
Any work arounds for this?

**Comment by rpanadero** [comment]
I'm facing the same problem. Is there a workaround?

**Comment by datawaslost** [comment]
Facing the same problem in recent capacitor builds - anyone have a solution? Perhaps use Cap storage instead of NativeStorage?

**Comment by THEDOWNCOUNTRY** [comment]
Share problem here and their seem to be no solution about this problem.
