### ISSUE TITLE
With the new Apple rules that (I think) required their native review widget, does this still work in iOS?

### ISSUE THREAD

**Issue by JamesLivengood** [pushandplay/cordova-plugin-apprate#238]
According to this: https://developer.apple.com/app-store/ratings-and-reviews/ , apps are required now to use Apple's review widget, using the SKStoreReviewController. Does anyone know if Cordova still works for Apple, and your app won't get banned for it?

**Comment by lights0123** [comment]
@JamesLivengood This plugin [does use SKStoreReviewController](https://github.com/pushandplay/cordova-plugin-apprate/blob/70b3ff73a77f11f1c57337d067bec49afbf094ae/src/ios/CDVAppRate.m#L85).
