### ISSUE TITLE
When simpleMode=true is set, inAppReview= true doesn't work

### ISSUE THREAD

**Issue by liuborama** [pushandplay/cordova-plugin-apprate#242]
When simpleMode=true is set, inAppReview= true doesn't work. 
On iOS 10.3 and above device, we can't show rating popup in app. just show the original popup
screen.

**Comment by tunguyen64** [comment]
I got it working once but then now it's not working anymore.

**Comment by bastenfeld** [comment]
Actually the in-app review message is limited to show **3 times a year,** so when you're developing this is triggered quickly. You can try it on another emulated device.
https://github.com/pushandplay/cordova-plugin-apprate/blob/master/www/AppRate.js#L268
