### ISSUE TITLE
"const"? ES6?

### ISSUE THREAD

**Issue by rodrigograca31** [pushandplay/cordova-plugin-apprate#243]
I was tracking down a problem in another plugin/script and realized this plugin uses ES6 features....
https://github.com/rossmartin/cordova-uglify/issues/46

How much can we rely on ES6?
Why not just use `var` instead of `const` ?

https://github.com/pushandplay/cordova-plugin-apprate/blob/c6d4953fb77eb21e53d6d60b2ff354210ea73986/www/AppRate.js#L300-L302

BTW, this code was introduced by this commit: https://github.com/pushandplay/cordova-plugin-apprate/commit/7bb820d1a347522517be0f309fb0ed2a584f9c5b

Since many apps still support Android 4.4 and I'd say the webview has not been updated to the latest standards on those devices I don't think we should use `const`
Also: https://caniuse.com/#feat=es6

Is it safe to use ES6 in Cordova projects? (my main app has 17 plugins with JavaScript and only this one uses `const` ...
Any thoughts? Should I make a pull request to change from `const` to `var`?

**Comment by westonganger** [comment]
Yes I support OG JS! Would love a PR, send it.
