### ISSUE TITLE
Question. Should the plugin fallback to in-app-browser rating if `inAppReview` is set to true

### ISSUE THREAD

**Issue by brad426** [pushandplay/cordova-plugin-apprate#250]
When `inAppReview` is set to `true`, and the plugin has already displayed more than 3 in-app notifications,  it does not fallback to the "in-app-browser" rating routine.

https://github.com/pushandplay/cordova-plugin-apprate/blob/738ee2ade3b6c3074f0b31939d86a15f6e11b4b2/www/AppRate.js#L266-L270

Is that the desired behaviour? or should the code look more like:
```
var showNativePrompt = iOSRating.timesPrompted < 3;
if (this.preferences.inAppReview && showNativePrompt) {
        updateiOSRatingData();
        exec(null, null, 'AppRate', 'launchiOSReview', [this.preferences.storeAppURL.ios, showNativePrompt]);
      } else {
...
```

**Comment by guylando** [comment]
wouldn't it annoy the user to keep redirecting him to store to rate the app after it was already displayed to him for 3 times?

**Comment by brad426** [comment]
Well, if the user taps "no thanks", indicating that they **never** want to rate the app, then yes, sure, it should never ask them again.

But if they click "rate it now" 
<img width="189" alt="Screenshot 2019-06-17 at 09 21 48" src="https://user-images.githubusercontent.com/686757/59585785-90a0a800-90e1-11e9-8d5d-1df284d6815f.png">
which brings up the native rating dialog (possibly for the 3rd and final time) and then they click "not now"
<img width="194" alt="Screenshot 2019-06-17 at 09 22 39" src="https://user-images.githubusercontent.com/686757/59585804-9a2a1000-90e1-11e9-9f11-ba44d95a5240.png">
they should be asked again sometime in the future, but will need to be sent to the app store

**Comment by guylando** [comment]
+1
I agree with you that the desired behavior is what you said [although this is a very extreme case of a user who clicked for 3 times "rate it now" only to then click "not now" (probably so extreme that it is unlikely to happen)]

**Comment by brad426** [comment]
True, it’s pretty unlikely.
What about the case of the user being offline? The prompt to rate would still come up right? If the user tried to rate by clicking “rate now” an attempt to rate would be tracked, but the native in app dialogue wouldn’t actually be displayed right? Anyways, I think these scenarios are all pretty unlikely. I think the issue can be closed.

**Comment by guylando** [comment]
@brad426 in our app the prompt will only be triggered on positive event and the trigger comes from the server and only in time close to the event. so if user has no internet connection at the time of the event then he will not get the event..probably a good idea though is to configure a timer which auto-closes the popup if it is still open in case it was opened when app is in background with internet on
