### ISSUE TITLE
iOS: No redirection to the star rating modal window

### ISSUE THREAD

**Issue by skopatsikas** [pushandplay/cordova-plugin-apprate#255]
Hello, our company is experiencing an issue on iOS while testing this plugin in Testflight. 
When the modal window asking the user if they would like to leave a rating with the options "Yes", "No" and "Later" is being displayed, and the user taps "Yes", it doesn't redirect/open the second modal window with the possibility to leave a star rating. Instead, it only closes the modal window and nothing else happens.
Help is very much appreciated.

**Comment by degroundshaker** [comment]
Same :(

**Comment by Yuripetusko** [comment]
It is not an issue, native app rate is not working in testflight version
