### ISSUE TITLE
can't get it working on ionic 4 - NullInjectorError: No provider for AppRate!

### ISSUE THREAD

**Issue by leabdalla** [pushandplay/cordova-plugin-apprate#256]
I've installed like docs says:

    ionic cordova plugin add cordova-plugin-apprate
    npm install --save @ionic-native/app-rate

Then I'm setting up in `app.component.ts` this way:

    import { AppRate } from '@ionic-native/app-rate/ngx';

    ...

    private appRate: AppRate,

    ...

    initializeApp() {

      this.platform.ready().then(() => {
        this.statusBar.styleDefault();
        this.splashScreen.hide();

        this.appRate.preferences = {
          displayAppName: 'Test App',
          usesUntilPrompt: 2,
          promptAgainForEachNewVersion: false,
          storeAppURL: {
            ios: '<my_app_id>',
            // android: 'market://details?id=<package_name>',
          },
          callbacks: {
            onRateDialogShow: function(callback){
              console.log('rate dialog shown!');
            },
            onButtonClicked: function(buttonIndex){
              console.log('Selected index: -> ' + buttonIndex);
            }
          }
        };
      });

    }

    async askToRate(){
      this.appRate.promptForRating(false);
    }

So when I open in browser, it shows a blank page with this console error:

    ERROR Error: StaticInjectorError(AppModule)[AppComponent -> AppRate]:
      StaticInjectorError(Platform: core)[AppComponent -> AppRate]:
        NullInjectorError: No provider for AppRate!

Am I doing something worngwrong?

**Comment by josevavia** [comment]
Same issue here. Any ideas?

**Comment by vosecek** [comment]
Add AppRate to providers: [] in app.module.ts.

**Comment by leabdalla** [comment]
Added to app.modules.ts solved that error, but it keep not working.

My current code is:

```typescript
  askToRate(){
    console.log('askToRate');
    this.appRate.preferences = {
      storeAppURL: {
        ios: 'xxxxxxxxx',
        android: 'market://details?id=com.parkaz.app',
      }
    };
    this.appRate.promptForRating(true);
  }
```

So when I click a button and call this method, I can see the `console.log('askToRate');` message but nothing happens after that.

Any idea?

**Comment by josevavia** [comment]
If anyone is here because the initial error (No provider for AppRate) and already have AppRate in providers[] in app.module.ts (that was my case), make sure the import line have `/ngx`:

```
import {AppRate} from '@ionic-native/app-rate/**ngx**';
```
My IDE by default added the line without `/ngx` and it was the source of the problem.

After that everything worked without errors.
