### ISSUE TITLE
feature: android in app review

### ISSUE THREAD

**Issue by GautierDele** [pushandplay/cordova-plugin-apprate#265]
Hello,

I'm just asking in Android in app review are in your roadmap ?
I'll have a look doing a PR this evening but not sure i'm enough qualified in cordova plugins.

Gautier

**Comment by westonganger** [comment]
@GautierDele I would love a PR for this. Android/Java development is fairly straight forward. Give it a shot and see how it goes.

**Comment by GautierDele** [comment]
I'm quite short on time for now but i'll write it on my task list

**Comment by westonganger** [comment]
Added to master via #281
