### ISSUE TITLE
Uncaught TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by medicopedia** [pushandplay/cordova-plugin-apprate#267]
`D/SystemWebChromeClient(19365): file:///android_asset/www/plugins/cordova-plugin-apprate/www/AppRate.js: Line 223 : Uncaught TypeError: Cannot read property 'then' of undefined`

`I/chromium(19365): [INFO:CONSOLE(223)] "Uncaught TypeError: Cannot read property 'then' of undefined", source: file:///android_asset/www/plugins/cordova-plugin-apprate/www/AppRate.js (223)`

**Comment by S-AT** [comment]
The same problem.

**Comment by georgiosd** [comment]
Same here, any ideas?

**Comment by georgiosd** [comment]
@medicopedia I fixed it by manually calling `AppRate.init()`

**Comment by Akeri** [comment]
Same problem.
Thanks to @georgiosd for the solution

**Comment by georgiosd** [comment]
@Akeri happy to contribute to good Google results 😆

**Comment by regevbr** [comment]
It happend to me as well. This is caused by a race condition of the deviceready event handlers. I hack/solved it by delaying the app rate interaction by 500 ms from the deviceready ever, giving a chance for the init method to finish
