### ISSUE TITLE
plugin work on cordova android 6.4.0 but not on latest 8.1.0

### ISSUE THREAD

**Issue by matrixreal** [pushandplay/cordova-plugin-apprate#269]
Hello guys,
this plugin is working on cordova android 6.4.0 but not on latest 8.1.0
any update? fixes?
thanks

**Comment by matrixreal** [comment]
on device ready i'm calling this
AppRate.preferences.storeAppURL.android = 'market://details?id=greedy.rabbit.bunny.run';
AppRate.preferences.usesUntilPrompt = 6;
AppRate.promptForRating(false);

**Comment by SiempreProgramadorNovato** [comment]
This code is working with latest version of cordova.. next time please provide more details so community could help in a better way

AppRate.init();
AppRate.preferences = {
  displayAppName: 'My GreatApp',
  usesUntilPrompt: 3,
  promptAgainForEachNewVersion: false,
  inAppReview: true,
  simpleMode: true,
  storeAppURL: {
    ios: '<my_app_id>',
    android: 'market://details?id=com.facebook.katana',
    windows: 'ms-windows-store://pdp/?ProductId=',
    blackberry: 'appworld://content/[App Id]/',
    windows8: 'ms-windows-store:Review?name='
  },
  customLocale: {
    title: "Rate My App",
    message: "My custom message",
    cancelButtonLabel: "No, Thank",
    laterButtonLabel: "Later",
    rateButtonLabel: "Rate Now",
    yesButtonLabel: "Yes!",
    noButtonLabel: "Not really",
    appRatePromptTitle: 'Do you like using %@',
    feedbackPromptTitle: 'Mind giving us some feedback?',
  },
  callbacks: {
    handleNegativeFeedback: function() {
      window.open('mailto:feedback@example.com', '_system');
    },
    onRateDialogShow: function(callback) {
      callback(1) // cause immediate click on 'Rate Now' button
    },
    onButtonClicked: function(buttonIndex) {
      console.log("onButtonClicked -> " + buttonIndex);
    }
  }
};

AppRate.preferences.openUrl = function(url) {
  window.open(url, '_blank', 'location=yes');
};
AppRate.promptForRating(); //you can put false here to use usesUntilPrompt instead
