### ISSUE TITLE
Add support for in-app reviews on Android

### ISSUE THREAD

**Issue by terreng** [pushandplay/cordova-plugin-apprate#276]
Add support for the new Google Play In-App Review API to enable in-app review prompts for Android devices. This would enable the `inAppReview` option to work on Android devices.

https://developer.android.com/guide/playcore/in-app-review
https://android-developers.googleblog.com/2020/08/in-app-review-api.html

**Comment by westonganger** [comment]
@terreng would appreciate a PR for this if you want to tackle it

**Comment by rodrigograca31** [comment]
I'd love to see this implemented since I use this plugin.

I'm no Java/Kotlin developer but there's some Kotlin code here that might help:
https://proandroiddev.com/google-play-in-app-review-api-integration-and-experience-a96b30805345
