### ISSUE TITLE
TypeError: Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by Syalcindag** [pushandplay/cordova-plugin-apprate#277]
First Erro :  TypeError: AppRate.preferences.openUrl is not a function 

Fixed with this solution -> https://github.com/pushandplay/cordova-plugin-apprate/issues/263#issuecomment-582651101

then , 

E/Capacitor/Console: File: capacitor-runtime.js - Line 362 - Msg: TypeError: Cannot read property 'open' of undefined
E/Capacitor: JavaScript Error: {"type":"js.error","error":{"message":"Uncaught TypeError: Cannot read property 'open' of undefined","url":"capacitor-runtime.js","line":1358,"col":21,"errorObject":"{}"}}
E/Capacitor/Console: File: capacitor-runtime.js - Line 1358 - Msg: Uncaught TypeError: Cannot read property 'open' of undefined

**Comment by regevbr** [comment]
It happend to me as well. This is caused by a race condition of the deviceready event handlers. I hack/solved it by delaying the app rate interaction by 500 ms from the deviceready ever, giving a chance for the init method to finish

**Comment by wal0x** [comment]
I had the same issue, and I solved it by instaling [In App Browser ](https://ionicframework.com/docs/native/in-app-browser)
