### ISSUE TITLE
annot read property 'then' of undefined. AppRate.js:223

### ISSUE THREAD

**Issue by oorabi** [pushandplay/cordova-plugin-apprate#278]
Today, App could not be open on all devices.
After debugging found this error.
TypeError: Cannot read property 'then' of undefined
    at Function.AppRate.promptForRating (/android_asset/www/plugins/cordova-plugin-apprate/www/AppRate.js:223)

**Comment by regevbr** [comment]
It happend to me as well. This is caused by a race condition of the deviceready event handlers. I hack/solved it by delaying the app rate interaction by 500 ms from the deviceready ever, giving a chance for the init method to finish
