### ISSUE TITLE
IOS native review bad UX experience

### ISSUE THREAD

**Issue by regevbr** [pushandplay/cordova-plugin-apprate#279]
According to https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview when launching IOS native in-app review, can have a non-deterministic behavior and can be shown or ignored without any notice. They specifically state:

> Because this method may or may not present an alert, it's not appropriate to call it in response to a button tap or other user action. 

This results in users clicking the rate now button with nothing happening afterward which is a bad UX.
I saw that previously you had a code to decide if to open the store or show the in-app rate dialog but you discarded it.
I think you should give control to the plugin user to decide if they want to keep the current behavior or force the native launch of the app store.
One can argue that you can just open the store link instead-but in WKWebView this renders impossible (they only allow http/s URLs to be opened).
I will create a PR that will add another configuration, to force the native launch of the app store, without the native in app rate
@westonganger thoughts?

**Comment by westonganger** [comment]
Thanks for digging into this. Yes I appreciate any way to improve things. Thanks for PR #280 we will continue the discussion over there.
