### ISSUE TITLE
Android set to inAppReview triggers callback but doesn't show anything

### ISSUE THREAD

**Issue by cerealexx** [pushandplay/cordova-plugin-apprate#284]
When setting preferences to:

```
reviewType: {
    ios: 'InAppReview',
    android: 'InAppReview'
 }
```

`onRateDialogShow` callback is triggered but nothing is shown on screen. Not even `openUrl` is triggered so it shouldn't be a matter of not being able to use `InAppReview` since documentation says that it would default to `InAppBrowser` in that case...

I'm using the git version because it seems the cordova plugins registry one doesn't have the Android in app rating feature. Also, it works in iOS.

**Comment by EinfachHans** [comment]
Have you tested this like it's [explained here](https://github.com/pushandplay/cordova-plugin-apprate#reviewtypeandroid-enum)?

**Comment by cerealexx** [comment]
Sorry, I thought the app being published was enough.
