### ISSUE TITLE
Incorrect logic in AppRate.showDialog method when customize the reviewType

### ISSUE THREAD

**Issue by Joe-song-77** [pushandplay/cordova-plugin-apprate#287]
With 1.60 version, the rating dialog will not be shown if there are the customized reviewType. 
E,g, 
AppRate.preferences = {
                  displayAppName: 'Fiori Client',
                  simpleMode: true,
                  reviewType: {
                    ios: 'InAppBrowser',
                    android: 'InAppBrowser'
                  },
}

To check the code logic in method showDialog of AppRate.js, I think there is wrong logic here. See below code snippet:
**_if (isNativePromptAvailable && AppRate.preferences.reviewType) {
        if ((IS_IOS && AppRate.preferences.reviewType.ios === 'InAppReview')
        || (IS_ANDROID && AppRate.preferences.reviewType.android === 'InAppReview')) {_**
                  updateCounter('stop');
                  AppRate.navigateToAppStore();
     } 
} else if(AppRate.preferences.simpleMode) {******}

The code logic will not go into else if block if there is customized reviewType. Probably, I think the code logic should be:
**_if (isNativePromptAvailable && AppRate.preferences.reviewType && ((IS_IOS && AppRate.preferences.reviewType.ios === 'InAppReview') || (IS_ANDROID && AppRate.preferences.reviewType.android === 'InAppReview'))) {_**
                  updateCounter('stop');
                  AppRate.navigateToAppStore();
} else if(AppRate.preferences.simpleMode) {***}

Could you please double check this? Thanks!

**Comment by westonganger** [comment]
v1.6.1 is now released which fixes this
