### ISSUE TITLE
Ionic 5 using native api capacitor - Override preferences is not working

### ISSUE THREAD

**Issue by josecarvalhoSigned** [pushandplay/cordova-plugin-apprate#292]
I'm using this code and when i try to override the default preferences don't work.
https://ionicframework.com/docs/native/app-rate

Any help??

**Comment by jderose9** [comment]
I had this issue too and was able to resolve it by using the AppRate property on the window. I don't know if there is a more "correct" way to do this.

```
window['AppRate'].setPreferences({
   // property: 'value',
});
```

Assigning the preferences property on the injected appRate instance doesn't work like I've seen suggested in other posts as accessing that preferences property writes a message to the console that the plugin isn't loaded.

**Comment by josecarvalhoSigned** [comment]
@jderose9 at this moment, using the AppRate property on the window, i was able to return the callback functions. But i still cannot override the custom messages, the title, the button names etc

**Comment by NLueg** [comment]
I have the same problem. I can override everything but the `customLocale`.

**Comment by NLueg** [comment]
This is fixed with 1.7.1

**Comment by josecarvalhoSigned** [comment]
I made the update to the version you mentioned but now in cant get any action.

Using this code as @jderose9 mentioned:
window['AppRate'].setPreferences({
   // property: 'value',
});

or using the code in ionic documentation: https://ionicframework.com/docs/native/app-rate

**Comment by NLueg** [comment]
Maybe try it the same as I do:

```ts
import AppRate from "cordova-plugin-apprate";

public showRatingPrompt() {
    AppRate.setPreferences({
      ...
    });

    AppRate.promptForRating(false);
}
```

This works perfectly for me.

**Comment by josecarvalhoSigned** [comment]
> Maybe try it the same as I do:
> 
> ```ts
> import AppRate from "cordova-plugin-apprate";
> 
> public showRatingPrompt() {
>     AppRate.setPreferences({
>       ...
>     });
> 
>     AppRate.promptForRating(false);
> }
> ```
> 
> This works perfectly for me.

Using like you said is returning this error:
![image](https://user-images.githubusercontent.com/44067633/99693129-f0437580-2a82-11eb-8465-e317c21fb235.png)

My project was created using Ionic Native + Capacitor + Angular

**Comment by NLueg** [comment]
Hm, that's very strange ... sorry about that. It works perfectly fine for me with the code I send you.

**Comment by petrot** [comment]
Please re-open this issue, it's still alive!

I've got the same issue... With Ionic, there is a native plugin what we have to use: `import { AppRate } from '@ionic-native/app-rate/ngx';`

With this plugin the preference update seems like this:

```
 this._appRate.preferences = {
        customLocale: {
          ...
        },
       displayAppName: '...',
       promptAgainForEachNewVersion: true,
       simpleMode: true,
       storeAppURL: {
         ....
       },
       useLanguage: 'hu',
       usesUntilPrompt: 4,
};
```

For me, this code now fails... The rate dialog appears, but with the default text.

**Comment by jderose9** [comment]
setPreferences still doesn't seem to be exposed anywhere in the types?

**Comment by petrot** [comment]
I created an issue in the ionic-native repo:

https://github.com/ionic-team/ionic-native/issues/3576

**Comment by NLueg** [comment]
> setPreferences still doesn't seem to be exposed anywhere in the types?

I actually would recommend you to use the typings of this very plugin like this

```ts
import AppRate from "cordova-plugin-apprate";
```

This will be maintained by the same people that maintain the native code so this will always be correct. I don't see any advantage of using the ionic-native package here
