### ISSUE TITLE
On Rate, browser opens localhost/null

### ISSUE THREAD

**Issue by pedrumgolriz** [pushandplay/cordova-plugin-apprate#295]
I'm not sure where I'm going wrong, I've used this plugin before without issue. Now with ionic 5 anytime a user clicks on the rate now button on the dialog, on android, the user ends up on a blank website with localhost/null in the address bar. On iOS the popped up dialog just spins then says could not connect. 

Config: 
"@ionic/angular": "^5.0.0",
"@ionic-native/app-rate": "^5.29.0",
"cordova-plugin-apprate": "1.7.1",

I've tried all configurations as seen below to no avail:
```
this.appRate.preferences = {
          simpleMode: true,
          storeAppURL: {
            ios: '123234',
            android: 'market://details?id=com.example.myapp'
          }
        };
        this.appRate.promptForRating(true);
```

```
this.appRate.preferences = {
          openUrl: function(url) {
            window.open(url, '_blank', 'location=yes');
          },
          simpleMode: true,
          storeAppURL: {
            ios: '123234',
            android: 'market://details?id=com.x.myapp'
          }
        };
        this.appRate.promptForRating(true);
```

```
this.appRate.preferences = {
          ...this.appRate.preferences,
          simpleMode: true,
          storeAppURL: {
            ios: '123234',
            android: 'market://details?id=com.example.myapp'
          }
        };
        this.appRate.promptForRating(true);
```

**Comment by simonramosb** [comment]
Hello! Having the same exact issue. Tried everything, lets hope somebody cand help us! 

Config:
Ionic CLI: 6.11.0
cordova-plugin-apprate: 1.7.1

`    let preferences = ({
      useLanguage: 'es',
      reviewType:{
        ios: 'AppStoreReview',
        android: 'InAppBrowser'
      },
      storeAppURL: {
        ios: '123123123',
        android: 'market://details?id=123123123',
      },
      simpleMode: true,
      displayAppName: 'xxxx',
      customLocale: {
        title: 'Te gusta?',
        message: 'Ayudanos a mejorar compartiendo tu opinión',
      }
    });

    this.appRate.preferences = preferences;
    this.appRate.promptForRating(true);
  }`

**Comment by simonramosb** [comment]
Hello! Having the same exact issue, same code as you. Tried everything, lets hope somebody cand help us! 

Config:
Ionic CLI: 6.11.0
cordova-plugin-apprate: 1.7.1

**Comment by akash-sr12** [comment]
Same issue 😕

**Comment by wnabil** [comment]
i confirm the plugin works fine and its `@ionic-native/app-rate` issue 
use the AppRate object from window and it should work as expected
```
    // tslint:disable-next-line: no-string-literal
    const appRate: any = window['AppRate'];
    const preferences = appRate.getPreferences();
    preferences.simpleMode = true;
    preferences.storeAppURL = {
      ios: 'id123456789',
      android: 'market://details?id=com.example.app',
      windows: 'ms-windows-store://review/?ProductId=XXXXXXXX',
    };
    appRate.setPreferences(preferences);
    appRate.promptForRating(true);
```
possible reference https://github.com/pushandplay/cordova-plugin-apprate/issues/291

**Comment by pedrumgolriz** [comment]
> i confirm the plugin works fine and its `@ionic-native/app-rate` issue
> use the AppRate object from window and it should work as expected
> 
> ```
>     // tslint:disable-next-line: no-string-literal
>     const appRate: any = window['AppRate'];
>     const preferences = appRate.getPreferences();
>     preferences.simpleMode = true;
>     preferences.storeAppURL = {
>       ios: 'id123456789',
>       android: 'market://details?id=com.example.app',
>       windows: 'ms-windows-store://review/?ProductId=XXXXXXXX',
>     };
>     appRate.setPreferences(preferences);
>     appRate.promptForRating(true);
> ```
> 
> possible reference #291

Awesome! Confirmed working for android, will test on iOS when I can. I'm going to leave this issue open as it should be fixed by the dev

**Comment by wnabil** [comment]
@pedrumgolriz
Glad it works.
its not going to be fixed here there is nothing to do with the current repo, better to report it in ionic native repo
https://github.com/ionic-team/ionic-native

**Comment by simonramosb** [comment]
> 
> 
> i confirm the plugin works fine and its `@ionic-native/app-rate` issue
> use the AppRate object from window and it should work as expected
> 
> ```
>     // tslint:disable-next-line: no-string-literal
>     const appRate: any = window['AppRate'];
>     const preferences = appRate.getPreferences();
>     preferences.simpleMode = true;
>     preferences.storeAppURL = {
>       ios: 'id123456789',
>       android: 'market://details?id=com.example.app',
>       windows: 'ms-windows-store://review/?ProductId=XXXXXXXX',
>     };
>     appRate.setPreferences(preferences);
>     appRate.promptForRating(true);
> ```
> 
> possible reference #291

Thanks a lot! Worked for me too!

**Comment by leabdalla** [comment]
Same problem here even using quoted solution code.

My package.json file has:

    "@angular/common": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@ionic-native/app-rate": "^5.29.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/in-app-browser": "^5.11.0",
    "@ionic/angular": "^4.8.0",
    "cordova-android": "^8.1.0",
    "cordova-browser": "6.0.0",
    "cordova-ios": "^5.1.1",
    "cordova-plugin-inappbrowser": "^4.1.0",

Someone can help?

Tried also many different plugin versions. It's driving me crazy.

**Comment by MrProscrite** [comment]
> i confirm the plugin works fine and its `@ionic-native/app-rate` issue
> use the AppRate object from window and it should work as expected
> 
> ```
>     // tslint:disable-next-line: no-string-literal
>     const appRate: any = window['AppRate'];
>     const preferences = appRate.getPreferences();
>     preferences.simpleMode = true;
>     preferences.storeAppURL = {
>       ios: 'id123456789',
>       android: 'market://details?id=com.example.app',
>       windows: 'ms-windows-store://review/?ProductId=XXXXXXXX',
>     };
>     appRate.setPreferences(preferences);
>     appRate.promptForRating(true);
> ```
> 
> possible reference #291

I tried this way and response: 
ERROR TypeError: Cannot read property 'getPreferences' of undefined
    at AppComponent.rateMe (app.component.ts:47)
    at AppComponent_Template_ion_item_click_15_listener (template.html:31)
    at executeListenerWithErrorHandling (core.js:14316)
    at wrapListenerIn_markDirtyAndPreventDefault (core.js:14351)
    at HTMLElement.<anonymous> (platform-browser.js:582)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:27425)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:480)
    
    

Config:
"@ionic/angular": "5.5.2",
"@ionic-native/app-rate": "5.31.1",
"cordova-plugin-apprate": "^1.7.2",
