### ISSUE TITLE
AppRate.js uses `let` identifier which is not supported on factory Android 5.1 (SDK 22)

### ISSUE THREAD

**Issue by jacobg** [pushandplay/cordova-plugin-apprate#298]
https://github.com/pushandplay/cordova-plugin-apprate/blob/5e0e250ec368fa36a86fa2238819e764c535f527/www/AppRate.js#L226

Throws this error:
```
SyntaxError · Unexpected identifier
file:///android_asset/www/plugins/cordova-plugin-apprate/www/AppRate.js:227:16f
```

Android 5.1 (SDK 22) factory install runs Chrome 39.

The fix would be to just use a `var` instead.

**Comment by westonganger** [comment]
This is now fixed in master

**Comment by westonganger** [comment]
v1.7.2 is now released which includes this fix.
