### ISSUE TITLE
iPad recognition not working

### ISSUE THREAD

**Issue by AndrejDaubert** [pushandplay/cordova-plugin-apprate#299]
The recognition for iPad over navigator.userAgent is not working in the current version. It return false and prevent the navigation to storepage.

File: AppRate.js
Line:  var IS_IOS = /(iPhone|iPod|iPad)/i.test(navigator.userAgent.toLowerCase());

Also see: 
https://stackoverflow.com/questions/57776001/how-to-detect-ipad-pro-as-ipad-using-javascript

**Comment by osben** [comment]
i added a fix
https://github.com/pushandplay/cordova-plugin-apprate/pull/300

**Comment by westonganger** [comment]
v1.7.2 is now released which includes this fix.
