### ISSUE TITLE
IOS 17.0.1 - Error "Call must be made on main thread"

### ISSUE THREAD

**Issue by Bradrickcruz** [pushandplay/cordova-plugin-apprate#327]
# Environment
macOS Sonoma 14.0
Cordova 10.0.0
cordova-ios 6.2
Xcode 15.0.1

Trying run app on "iPad(10th gen) 17.0.1"

# Issue
When my app runs ```AppRate.navigateToAppStore();```, it crashes the app. It seems occur because it runs on another thread not the main thread on iOS devices. The error log is below:
![erro_ipad](https://github.com/pushandplay/cordova-plugin-apprate/assets/38919411/49b322c2-695b-4c30-afdd-dff2b62744ca)

On iOS 16 devices it still working fine, but on iOS 17+ not.
How could I change the thread that calls this function to the main thread?

**Comment by msd117** [comment]
Facing the same issue... did you find any fix @Bradrickcruz

**Comment by hoggMan** [comment]
Same issue. Crashes the app on iOS 17 when choosing to rate now. "Call must be made on the main thread".

**Comment by jellomaster** [comment]
There haven't been updates to this plugin in over 2 years.  You need to put the code into:
dispatch_async(dispatch_get_main_queue(), ^{
});

ex.. this should fix it:
- (void)launchAppStore:(NSString *) appId{
    [self.commandDelegate runInBackground:^{
        // Initialize Product View Controller
        dispatch_async(dispatch_get_main_queue(), ^{
            SKStoreProductViewController *storeProductViewController = [[SKStoreProductViewController alloc] init];

            // Configure View Controller
            [storeProductViewController setDelegate:self];
            [storeProductViewController loadProductWithParameters:@{SKStoreProductParameterITunesItemIdentifier : appId} completionBlock:^(BOOL result, NSError *error) {
                if (error) {
                    NSLog(@"Error %@ with User Info %@.", error, [error userInfo]);
                } else {
                        [UIApplication sharedApplication].networkActivityIndicatorVisible = NO;
                }
            }];
            [self.viewController presentViewController:storeProductViewController animated:YES completion:nil];
            
        });
    }];
}

**Comment by msd117** [comment]
@jellomaster  Thanks I ll check this today

> There haven't been updates to this plugin in over 2 years. You need to put the code into: dispatch_async(dispatch_get_main_queue(), ^{ });
> 
> ex.. this should fix it:
> 
> ```
> - (void)launchAppStore:(NSString *) appId{
>     [self.commandDelegate runInBackground:^{
>         // Initialize Product View Controller
>         dispatch_async(dispatch_get_main_queue(), ^{
>             SKStoreProductViewController *storeProductViewController = [[SKStoreProductViewController alloc] init];
> 
>             // Configure View Controller
>             [storeProductViewController setDelegate:self];
>             [storeProductViewController loadProductWithParameters:@{SKStoreProductParameterITunesItemIdentifier : appId} completionBlock:^(BOOL result, NSError *error) {
>                 if (error) {
>                     NSLog(@"Error %@ with User Info %@.", error, [error userInfo]);
>                 } else {
>                         [UIApplication sharedApplication].networkActivityIndicatorVisible = NO;
>                 }
>             }];
>             [self.viewController presentViewController:storeProductViewController animated:YES completion:nil];
>             
>         });
>     }];
> }
> ```

I ll check this today

**Comment by hoggMan** [comment]
> There haven't been updates to this plugin in over 2 years. You need to put the code into: dispatch_async(dispatch_get_main_queue(), ^{ });
> 
> ex.. this should fix it:
> 
> ```
> - (void)launchAppStore:(NSString *) appId{
>     [self.commandDelegate runInBackground:^{
>         // Initialize Product View Controller
>         dispatch_async(dispatch_get_main_queue(), ^{
>             SKStoreProductViewController *storeProductViewController = [[SKStoreProductViewController alloc] init];
> 
>             // Configure View Controller
>             [storeProductViewController setDelegate:self];
>             [storeProductViewController loadProductWithParameters:@{SKStoreProductParameterITunesItemIdentifier : appId} completionBlock:^(BOOL result, NSError *error) {
>                 if (error) {
>                     NSLog(@"Error %@ with User Info %@.", error, [error userInfo]);
>                 } else {
>                         [UIApplication sharedApplication].networkActivityIndicatorVisible = NO;
>                 }
>             }];
>             [self.viewController presentViewController:storeProductViewController animated:YES completion:nil];
>             
>         });
>     }];
> }
> ```

This worked for me! Thanks @jellomaster

**Comment by westonganger** [comment]
@jellomaster it would be really nice if you could create a PR for this fix. We are always happy to have contributions, your time will not be wasted.

**Comment by msd117** [comment]
> There haven't been updates to this plugin in over 2 years. You need to put the code into: dispatch_async(dispatch_get_main_queue(), ^{ });
> 
> ex.. this should fix it:
> 
> ```
> - (void)launchAppStore:(NSString *) appId{
>     [self.commandDelegate runInBackground:^{
>         // Initialize Product View Controller
>         dispatch_async(dispatch_get_main_queue(), ^{
>             SKStoreProductViewController *storeProductViewController = [[SKStoreProductViewController alloc] init];
> 
>             // Configure View Controller
>             [storeProductViewController setDelegate:self];
>             [storeProductViewController loadProductWithParameters:@{SKStoreProductParameterITunesItemIdentifier : appId} completionBlock:^(BOOL result, NSError *error) {
>                 if (error) {
>                     NSLog(@"Error %@ with User Info %@.", error, [error userInfo]);
>                 } else {
>                         [UIApplication sharedApplication].networkActivityIndicatorVisible = NO;
>                 }
>             }];
>             [self.viewController presentViewController:storeProductViewController animated:YES completion:nil];
>             
>         });
>     }];
> }
> ```

Worked for me as well thanks @jellomaster
