### ISSUE TITLE
Compiling targetSDK=34, com.google.android.play:core

### ISSUE THREAD

**Issue by graphefruit** [pushandplay/cordova-plugin-apprate#332]
Hey there,
I've just published a new release of my app, and updated to targetSDK 34, and got following information of android:

If your app is targeting SDK 34+ (targetSdkVersion), then the PlayCore SDK is outdated and will likely cause crashes in your app! Please update: https://developer.android.com/guide/playcore#playcore-migration

Is there any plans to upgrade to the kotlin libraries?

**Comment by brunochikuji** [comment]
Hi, I also need this adjustment.

Google Play is requesting migration when sending a new version of the app

**Comment by xavierserrainnofis** [comment]
Dears,

Is there any update planned for it?

Thanks

**Comment by xavierserrai** [comment]
Dears,

Is there any planned update on this issue?

Thanks,

**Comment by ryaa** [comment]
This PR https://github.com/pushandplay/cordova-plugin-apprate/pull/334 should resolve the issue. Can someone test it by installing the updated plugin from my fork repo branch by issuing the below command (note that I used the below to install it in my capacitor based app, so you may need to install it differently)
`npm install ryaa/cordova-plugin-apprate#chore/migration-from-play-core-sdk`

**Comment by xavierserrai** [comment]
I have installed it into a cordova app with the following command:

`cordova plugin add git@github.com:ryaa/cordova-plugin-apprate.git`

Builds and runs properly. However I cannot test the InAppReviewService popup as I am missing an internal app sharing environment.

**Comment by ryaa** [comment]
> However I cannot test the InAppReviewService popup as I am missing an internal app sharing environment.

Can you open the android project in Android Studio, build and install from it to test? I think that it should work....

**Comment by xavierserrai** [comment]
I have launched it from Android Studio. I launch the rate plugin and the following popups appear:

1.- Do you like using xxx app? - > Click yes
2.- Enjoying xxx app? (three buttons) -> Click Rate it now
3.- No more popups appear
4.- Logcat logs:

`2024-06-26 16:40:33.531 22601-22770 PlayCore                com.riyadbank.strategic              I  UID: [10287]  PID: [22601] ReviewService : requestInAppReview (com.riyadbank.strategic)
2024-06-26 16:40:33.532 22601-22601 WindowOnBackDispatcher  com.riyadbank.strategic              W  sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@207399286 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@bdf3322
2024-06-26 16:40:33.535 22601-23159 PlayCore                com.riyadbank.strategic              I  UID: [10287]  PID: [22601] ReviewService : Initiate binding to the service.
2024-06-26 16:40:33.567 22601-22601 PlayCore                com.riyadbank.strategic              I  UID: [10287]  PID: [22601] ReviewService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.inappreviewservice.InAppReviewService})
2024-06-26 16:40:33.567 22601-23159 PlayCore                com.riyadbank.strategic              I  UID: [10287]  PID: [22601] ReviewService : linkToDeath
2024-06-26 16:40:33.609 22601-22614 PlayCore                com.riyadbank.strategic              I  UID: [10287]  PID: [22601] OnRequestInstallCallback : onGetLaunchReviewFlowInfo
2024-06-26 16:40:33.609 22601-23159 PlayCore                com.riyadbank.strategic              I  UID: [10287]  PID: [22601] ReviewService : Unbind from service.`

However, having googled a bit seems that to test it properly and see the rate popup you need to upload the app to an internal testing environment or internal app sharing.

https://stackoverflow.com/questions/63286540/play-core-in-app-review-api-not-showing-the-review-activity/65333746#65333746

Thanks,

**Comment by ryaa** [comment]
> However, having googled a bit seems that to test it properly and see the rate popup you need to upload the app to an internal testing environment or internal app sharing.

I can test the plugin by installing the app from Android Studio, but, I'm the internal tester in my app on the google play.

**Comment by ryaa** [comment]
> Is it working ok for you? If it is working for you I think we can consider that testing has been successful.

Yes. I have installed the plugin from my forked repo and it works fine.

**Comment by westonganger** [comment]
This issue should now be fixed on the master branch. Thanks to @ryaa for his contribution.

**Comment by xavierserrai** [comment]
Thanks a lot. When is it planned to be released?

**Comment by westonganger** [comment]
Can you please use the master branch for a bit first please. Let's fully verify the PR before releasing a version.

**Comment by xavierserrai** [comment]
Sure. I will test again from the master branch. Thanks.

**Comment by AM-Myrick** [comment]
Any news on when this is planned to be released?

**Comment by westonganger** [comment]
Thanks for testing guys. The fix for this is now released in v1.8.0
