### ISSUE TITLE
Confusion with ng-Cordova

### ISSUE THREAD

**Issue by rodneyjoyce** [pushandplay/cordova-plugin-apprate#64]
Hi,

Thanks for this plugin. I am trying to use it with Ionic and ng-Cordova. I have added the plug-in and downloaded the latest ng-Cordova. 

As per http://ngcordova.com/docs/plugins/appRate/ - I can get the Popup to display with 
              $cordovaAppRate.promptForRating(true).then(function (result) {                    });

However, it does not seem to expose the Preferences method. 

For example, this will throw an error:

$cordovaAppRate.preferences.storeAppURL.ios = '<my_app_id>';

Can you please post some guidelines on how to use this plug when used through ng-Cordova?

**Comment by pushandplay** [comment]
@rodneyjoyce Hi, implementation of AppRate plugin for ng-Cordova is not official and I not support this. You can ask about your problem ng-Cordova developers

**Comment by rodneyjoyce** [comment]
Ok, thanks for the quick response. I will do that

**Comment by pushandplay** [comment]
@rodneyjoyce Try use AppRate plugin without ng-Cordova wrapper

**Comment by rodneyjoyce** [comment]
Thanks - that has been more successul. I just don't understand what the point of the ng-Cordova library is then - it is as easy just to use the plugins directly?

**Comment by pushandplay** [comment]
For my opinion this only for pushing new Ionic technology, and noise around AngularJS. But looks like as wrapper for wrapper.
