### ISSUE TITLE
In order to compile on Android with Eclipse/ADT, needed to change package name

### ISSUE THREAD

**Issue by rajatrocks** [pushandplay/cordova-plugin-apprate#65]
in AppRate.java from **package org.apache.cordova.apprate;** 

to 

**package org.apache.cordova.apprate;**

**Comment by pushandplay** [comment]
@rajatrocks What? see #58

**Comment by rajatrocks** [comment]
Sorry, cut and pasted poorly. I had to change the code in platforms/android/src/org/apache/cordova/apprate/AppRate.java from **package org.pushandplay.cordova.apprate;** to **package org.apache.cordova.apprate;**

I didn't look through closed issues before, apologies. Seems like it's still a problem though?

**Comment by rajatrocks** [comment]
Actually, this fix didn't work. What did work was to move AppRate.java to org/pushandplay/cordova/apprate

**Comment by westonganger** [comment]
This should be corrected in the latest version, please upgrade and let me know if this is still occuring.
