### ISSUE TITLE
Bypass dialog and go straight to market?

### ISSUE THREAD

**Issue by djett41** [pushandplay/cordova-plugin-apprate#67]
Is there a way to bypass the dialog popup and go straight to market?  Say I have a setting list item that says "Rate this app".  If a user clicks it I want to go straight to the app store rather than prompt them with a dialog box.  Is this available in this plugin?

Thanks!

**Comment by pushandplay** [comment]
@djett41 Hi. Yes, it's possible. Fill links to your app in preferences object and call <code>AppRate.navigateToAppStore()</code> method. See source code for more details.

**Comment by djett41** [comment]
After digging through the code, looks like this is just a window.open from the javascript with the ios/android URLs.  Might be a nice little enhancement though to add functionality to do this from the plugin :)

**Comment by djett41** [comment]
nice!! Thanks @pushandplay disregard my last statement, didnt know this was publicly available in the plugins API .  Thanks again!

**Comment by pushandplay** [comment]
@djett41 You can install <code>org.apache.cordova.inappbrowser</code> plugin and call <code>window.open</code> without AppRate plugin.

**Comment by pushandplay** [comment]
@djett41 Where are you from? Which country?

**Comment by pushandplay** [comment]
@djett41 And one more: play on iOS with <code>openStoreInApp</code> in preferences object

**Comment by djett41** [comment]
USA @pushandplay .  I actually wanted to link out to ios app store/google play rather than opening from within the app.  calling AppRate.navigateToAppStore() from within my app is exactly what im looking for thanks!
