### ISSUE TITLE
Custom Locale Not Working

### ISSUE THREAD

**Issue by Purus** [pushandplay/cordova-plugin-apprate#68]
I am not able to create a custom locale for the AppRate plugin. Even after changing the locale, it's still showing in English.

I did as per the instructions in https://github.com/pushandplay/cordova-plugin-apprate

```JavaScript
module.config(function($cordovaAppRateProvider) {

    document.addEventListener("deviceready", function() {
        var customLocale = {};
        customLocale.title = "Rate %@";
        customLocale.message = "Rate %@ now?";
        customLocale.cancelButtonLabel = "No, Thanks";
        customLocale.laterButtonLabel = "Remind Me Later";
        customLocale.rateButtonLabel = "Rate It Now";

        var prefs = {
            //language: 'en',
            appName: 'Designs',
            customLocale: customLocale,
            androidURL: 'market://details?id=dfdfdf'
        };

        $cordovaAppRateProvider.setPreferences(prefs)

    }, false);
});
```

**Comment by pushandplay** [comment]
@Purus Hi, implementation of AppRate plugin for ng-Cordova is not official and I not support this. You can ask about your problem ng-Cordova developers. For solution use AppRate plugin without ngCordova wrapper. see similar issue #64

**Comment by Purus** [comment]
Thanks @pushandplay for this good plugin. I will contact ngCordova team.
