### ISSUE TITLE
Plugin aren't work

### ISSUE THREAD

**Issue by wap4444** [pushandplay/cordova-plugin-apprate#69]
Hi! I tryed to install this plugin via instructions...But after it i see this
http://prntscr.com/60wcda

http://prntscr.com/60wch1

What's wrong?

**Comment by wap4444** [comment]
Я не понял как можно установить для андроид?

**Comment by pushandplay** [comment]
@wap4444 try make pull from branch [feature/ISSUE-69](https://github.com/pushandplay/cordova-plugin-apprate/tree/feature/ISSUE-69)

**Comment by wap4444** [comment]
I can't understand what I must do..
I enter in CMD "cordova plugins add https://github.com/pushandplay/cordova-plugin-apprate.git"
then enter my app url for GoogleStore....
What's wrong?

**Comment by pushandplay** [comment]
@wap4444 clon repo from branch and install from local folder <code>$ cordova plugin add ../my_plugin_dir</code>. http://cordova.apache.org/docs/en/4.0.0/guide_cli_index.md.html

**Comment by wap4444** [comment]
Ok! I install it....but I do not see any apprate window..
here's  my code:
    storeAppURL: {
      ios: null,
      android: 'market://details?id=com.restaurant.start',
      blackberry: null,
      windows8: null
    },
....
  AppRate.promptForRating = function(immediately) {
    if (immediately == null) {
      immediately = true;
    }

**Comment by pushandplay** [comment]
@wap4444 read docs

AppRate.preferences.storeAppURL.android = 'market://details?id=com.restaurant.start';
AppRate.promptForRating(true);

**Comment by wap4444** [comment]
mmmm....((( can't understand

Where should I insert?
AppRate.preferences.storeAppURL.android = 'market://details?id=com.restaurant.start';
AppRate.promptForRating(true);

in \www\plugins\org.pushandplay.cordova.apprate\AppRate.js   ???
