### ISSUE TITLE
Cordova plugin add conflicts

### ISSUE THREAD

**Issue by alxpereira** [pushandplay/cordova-plugin-apprate#74]
Hi,
I've just experienced an issue adding your plugin to my iOS project.
It looks like the configuration xml isn't doing his job properly has it was missing some dependencies to make this plugin work. 

Plugins installed : 
notifications
globalization
apprate

Missing Build Phases Compiled Sources : 
CDVNotification.m
CDVGlobalization.m

Missing Binary :
AudioToolbox.framework

It might be a conflict with other plugins as i'm using a couple of them.
Thx
Alex

**Comment by pushandplay** [comment]
@alxpereira Hi, ok I will check it, tnx

**Comment by westonganger** [comment]
This should be fixed in latest version. the AudioToolbox is an error related to your app not this plugin. Closed.
