### ISSUE TITLE
How to setup the plugin in intel XDK 

### ISSUE THREAD

**Issue by Alexandr951** [pushandplay/cordova-plugin-apprate#75]
Where should I put the code:
AppRate.preferences.storeAppURL.ios = '<my_app_id>';
AppRate.promptForRating(true);

to intelxdk.config.additions.xml ? or create script on page ?

**Comment by bloodguard** [comment]
In the project tab in the Plugins/Third party plugin you click on Get Plugin from web.
Then, you put AppRate for name  and for the plugin ID you add org.pushandplay.cordova.apprate and check the check box.
The plugin is now added but BE WARNED, the plugin can only be tested trough the build tab.
Also for your code, you should read those article so you can now where and when to prompt the rate dialog.
http://www.loopinsight.com/2014/02/04/begging-for-app-ratings/
http://www.cowlyowl.com/blog/app-store-reviews
