### ISSUE TITLE
Add Amazon-FireOS support

### ISSUE THREAD

**Issue by revie** [pushandplay/cordova-plugin-apprate#76]
Would love to see Amazon FireOS support added, and seems like adding support would be fairly simple.  Amazon uses the following URL format for accessing the details from within the Amazon App Store app:

   amzn://apps/android?asin=<Amazon ASIN App ID>

For me, all it took was duplicating the "android" platform in "plugin.xml" for the "amazon-fireos" platform, then adding the following just before the Android check on www/AppRate.js (needs to be before the Android check, since Amazon apps are Android apps):

    } else if (/(Amazon)/i.test(navigator.userAgent.toLowerCase())) {
      window.open(this.preferences.storeAppURL.amazon, '_system');
    } else if (/(Android)/i.test(navigator.userAgent.toLowerCase())) {

and finally adding the following to my setup code:

    AppRate.preferences.storeAppUrl.amazon = 'amzn://apps/android?asin=<asin_number>';

Amazon docs:
Linking instructions: https://developer.amazon.com/appsandservices/apis/earn/in-app-purchasing/docs/deeplink
User agent strings: https://developer.amazon.com/public/solutions/platforms/webapps/faq

**Comment by revie** [comment]
FireOS is now deprecated in Cordova 6.0.  No longer needed.

**Comment by rodrigograca31** [comment]
@revie 
Any way to know if someone installed the app throutgh Amazon App store? So that we can send them to the Amazon App page to review the app?

**Comment by revie** [comment]
Absolutely:  ionic.Platform.isAndroid() && window.navigator.userAgent.match(/\bfireos\b/i)

**Comment by revie** [comment]
Absolutely.  If they installed through the Amazon App store, then the window.navigator.userAgent will tell you, such as:

if (/(Amazon)/i.test(navigator.userAgent))

**Comment by rodrigograca31** [comment]
Doens't cordova bundle chrome/chromium webview...? doesn't that mean that it will return "Chrome/Android" in `navigator.userAgent`?
Ins't it just like a normal app but installed through Amazon underground...?

Would this work?
```javascript
if (/(Amazon)/i.test(navigator.userAgent))
    AppRate.preferences.storeAppURL.android = 'amzn://apps/android?asin=<asin_number>';
```

**Comment by rodrigograca31** [comment]
Using that URL scheme works. 
But my Android always returns "`Android`" in the userAgent... Not sure what device will return "`Amazon`" but this code works:
```javascript
if (/(Amazon)/i.test(navigator.userAgent)) {
    AppRate.preferences.storeAppURL.android = 'amzn://apps/android?asin=<asin_number>';
}
```
