### ISSUE TITLE
Bug: Illegal Access on Android 2.3

### ISSUE THREAD

**Issue by revie** [pushandplay/cordova-plugin-apprate#77]
Received the following exception when running on Android 2.3:

   file:///android_asset/www/plugins/org.pushandplay.cordova.apprate/www/AppRate.js: Line 136 : Uncaught illegal access

Apparently, JSON.parse() on Android 2.3 throws that error when the value to be parsed is NULL:

   http://zsitro.com/html5-localstorage-illegal-access-bugfix/

Fixed the issue with the following code:

  AppRate.init = function() {
    var data = localStorageParam(LOCAL_STORAGE_COUNTER);
    counter = data ? JSON.parse(data) : counter;

**Comment by westonganger** [comment]
Fixed in master. Will be released in v1.2.0
