### ISSUE TITLE
cordova 5.0 cli "rename" problem

### ISSUE THREAD

**Issue by bau720123** [pushandplay/cordova-plugin-apprate#83]
hi @pushandplay 
I am using cordova 5.0 cli
there is a new "rename" problem
all detail at here
http://www.littlebau.com/cli/apprate_cli.gif
http://cordova.apache.org/

**Comment by westonganger** [comment]
This plugins `plugin.xml` was recently updated. Can you try updating to the latest version (1.1.9 currently) and let me know if this is still an issue.
