### ISSUE TITLE
Crash on first time app launch

### ISSUE THREAD

**Issue by kaiserlos** [pushandplay/cordova-plugin-apprate#84]
Hi,

I am trying to use this plugin with appgyver steroids which is using cordova 3.8 for ios. Basically the plugin works but it crash if I newly installed my app and launch it the very first time. After that everything works fine.

The big problem is: Apple is rejecting the app because of this.

Any ideas?

**Comment by westonganger** [comment]
This plugins `plugin.xml` was recently updated. Can you try updating to the latest version (1.1.9 currently) and let me know if this is still an issue.
