### ISSUE TITLE
%@ instead of name of the app

### ISSUE THREAD

**Issue by adantart** [pushandplay/cordova-plugin-apprate#93]
I see "%@" instead of name of the app ... any clue ?

I'm using this code:

```
var customLocale = {};
customLocale.title = "Rate %@ !";
customLocale.message = "Did you enjoy %@? Please rate us!";
customLocale.cancelButtonLabel = "No, Thanks";
customLocale.laterButtonLabel = "Remind Me Later";
customLocale.rateButtonLabel = "Rate It Now";

AppRate.preferences.openStoreInApp = true;
AppRate.preferences.storeAppURL.ios = '123123123123123';
AppRate.preferences.storeAppURL.android = 'market://details?id=com.test';
AppRate.preferences.customLocale = customLocale;
AppRate.preferences.displayAppName = 'name of my app';
AppRate.preferences.usesUntilPrompt = 5;
AppRate.preferences.promptAgainForEachNewVersion = false;
AppRate.promptForRating(true);
```

Other question, when I use the callback(3) to trigger the "rate now" with a custom button of "Rate this app" in my view, I can see the window popup and then goes to the market ... it's not nice to see a popup window for a second and then a jump to other page ... is there any chance to now show the popup window when triggering the callback ?

THANK YOU !
##

**Comment by westonganger** [comment]
Is this issue still occuring in the latest version?

**Comment by SharkChips** [comment]
Yes, I can confirm this issue is still present.

**Comment by westonganger** [comment]
This was related to using a `customLocale`. Just release v1.3.0 which fixes this.
