### ISSUE TITLE
Take the user directly to rating view on iOS App Store

### ISSUE THREAD

**Issue by valnub** [pushandplay/cordova-plugin-apprate#95]
On iOS, if the user hits yes in the prompt he will get redirected to the details page of the app.
Imho, he should be directly sent to the rating view instead.
You can do that by using this url shema:

[http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewContentsUserReviews?id=APP_ID_HERE&pageNumber=0&sortOrdering=1&type=Purple+Software&mt=8](http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewContentsUserReviews?id=APP_ID_HERE&pageNumber=0&sortOrdering=1&type=Purple+Software&mt=8)

Replace `APP_ID_HERE` with the id of the app.

I created a PR for that, see #96

**Comment by filipefreitas82** [comment]
+1

**Comment by westonganger** [comment]
#96 merged
