### ISSUE TITLE
Init plugin ?

### ISSUE THREAD

**Issue by Guih44** [pushandplay/cordova-plugin-apprate#97]
Hi

i try this plugin but it doesn't work.

How do you bootstrap it ? 

is there anything to declare before using it ? 

I try this simple code : 

	AppRate.preferences.storeAppURL.ios = '<my_app_id>';
	AppRate.preferences.storeAppURL.android = 'market://details?id=<package_name>';
	AppRate.preferences.storeAppURL.blackberry = 'appworld://content/[App Id]/';
	AppRate.preferences.storeAppURL.windows8 = 'ms-windows-store:Review?name=<the Package Family Name of the application>';
	AppRate.promptForRating();

But it doen't work. 

I try this : 

console.log(AppRate);

But result is : 

function AppRate() {}

Thanks !

**Comment by bmarci** [comment]
I have the same issue here. I think this being a cordova plugin we don't have to declare.

**Comment by bmarci** [comment]
I fixed it calling it after device ready and instead of AppRate.promptForRating(); I do AppRate.promptForRating(true);
