### ISSUE TITLE
Updating to the latest Cordova version (5.4.0) breaks the plugin.

### ISSUE THREAD

**Issue by SMJ93** [pushandplay/cordova-plugin-apprate#99]
It was working fine before this update.

The build is still successful, but once onDeviceReady triggers I get the error:

`Can't find variable AppRate`

This refers to:

        AppRate.preferences.openStoreInApp = true;
        AppRate.preferences.storeAppURL.ios = '########';
        AppRate.preferences.customLocale = customLocale;
        AppRate.preferences.displayAppName = '########';
        AppRate.preferences.usesUntilPrompt = 5;
        AppRate.preferences.promptAgainForEachNewVersion = false;
        AppRate.promptForRating();

**Comment by danieltamiosso** [comment]
Hi @SMJ93, any news?

**Comment by westonganger** [comment]
This plugins `plugin.xml` was recently updated. Can you try updating to the latest version (1.1.9 currently) and let me know if this is still an issue.

**Comment by JoseRoman** [comment]
@SMJ93 @westonganger I know this is super old but I was wondering if you guys remember how to fix this? I'm getting the same error on an old ionic app and I couldn't find any other resource online apart from this issue

**Comment by SMJ93** [comment]
@JoseRoman  @danieltamiosso I decided to create my own solution which would display a popup box with 5 stars and then send the rating to an custom endpoint before forwarding the user to the relevant App in the App Store. Sorry for the late response!
